package com.aerogroup.mcpanel;

import javafx.beans.property.*;
import javafx.beans.value.ChangeListener;
import javafx.scene.*;
import javafx.scene.control.*;
import javafx.scene.layout.Pane;
import java.io.*;
import java.nio.file.*;
import java.util.*;

/** Statik ve sonradan değişen arayüz metinlerini Türkçe/İngilizce yerelleştirir. */
public final class LanguageManager {
    private static final Path FILE = Path.of(System.getProperty("user.home"), ".aeromc-panel", "ui.properties");
    private static final Map<String, String> TR_EN = new LinkedHashMap<>(), EN_TR = new HashMap<>();
    private static final BooleanProperty ENGLISH = new SimpleBooleanProperty(false);
    private static final String LABEL_LISTENER = "aeromc.i18n.label", PROMPT_LISTENER = "aeromc.i18n.prompt";
    private static boolean changing;
    static {
        putAll(new String[][]{
            {"Ana Panel","Dashboard"},{"Yerel JAR","Local JAR"},{"Yönetim","Management"},{"Pro Araçlar","Pro Tools"},{"Canlı Harita","Live Map"},{"Araçlar","Tools"},{"Ayarlar","Settings"},{"Kurulum","Setup"},{"Uyumluluk","Compatibility"},{"Yedekler","Backups"},{"Optimizasyon","Optimization"},{"Uzaktan Erişim","Remote Access"},{"Dil & Görünüm","Language & Appearance"},{"Performans & Log","Performance & Log"},{"Dosyalar","Files"},{"Eklenti & Mod","Plugin & Mod"},{"Dünyalar","Worlds"},{"Otomasyon","Automation"},{"Görevler & Bildirimler","Tasks & Notifications"},{"Oyuncu Profilleri","Player Profiles"},
            {"AeroGuard hakkında bilgi","About AeroGuard"},{"AeroGuard V2.3","AeroGuard V2.3"},{"AeroMC'nin etkin güvenlik katmanı","AeroMC's active security layer"},{"AeroGuard; sunucu dosyalarını, API anahtarlarını, uzaktan erişimi ve kritik yönetim işlemlerini tek güvenlik katmanında korur.","AeroGuard protects server files, API keys, remote access, and critical management actions through one security layer."},{"• SafePathGuard ile klasör dışına ve simgesel bağlantılara kaçışı engeller.\n• Kritik konsol komutlarında kullanıcı onayı ve uzaktan salt okunur komut listesi uygular.\n• Gizli bilgileri AES-256-GCM kasasında, 600.000 turlu anahtar türetmeyle saklar.\n• Uzaktan erişimi TLS ile şifreler; hız sınırı, sıkı istek doğrulaması ve tek kullanımlık CSP nonce'ları uygular.\n• Dosya izinlerini, veri sınırlarını, güncelleme sağlama toplamlarını ve çökme döngülerini denetler.","• SafePathGuard blocks path traversal and symbolic-link escapes.\n• Critical console commands require confirmation and remote commands use a read-only allowlist.\n• Secrets use AES-256-GCM vaults with 600,000-round key derivation.\n• Remote access uses TLS, rate limits, strict request validation, and one-time CSP nonces.\n• File permissions, data limits, update checksums, and crash loops are monitored."},{"Durum: AeroGuard V2.3 etkin ve korumalar çalışıyor.","Status: AeroGuard V2.3 is active and protections are running."},
            {"▶ Sunucuyu Başlat","▶ Start Server"},{"▶ Başlat","▶ Start"},{"■ Durdur","■ Stop"},{"↻ Yeniden Başlat","↻ Restart"},{"Başlat","Start"},{"Durdur","Stop"},{"Yeniden Başlat","Restart"},{"Yedek Al","Create Backup"},{"Gönder","Send"},{"Bağlan","Connect"},{"Yenile","Refresh"},{"Şimdi Yenile","Refresh Now"},{"Dosya Seç","Choose File"},{"Klasör Seç","Choose Folder"},{"Yükle","Load"},{"Kaydet","Save"},{"Güvenli Kaydet","Safe Save"},{"Seçileni Sil","Delete Selected"},{"Geri Yükle","Restore"},{"Hazır","Ready"},{"Kapalı","Disabled"},{"Bilinmiyor","Unknown"},{"Kontrol ediliyor...","Checking..."},{"Kontrol bekleniyor","Waiting for check"},{"Adres gerekli","Address required"},
            {"SUNUCU AYARLARI","SERVER SETTINGS"},{"CANLI KONSOL","LIVE CONSOLE"},{"CANLI EXAROTON KONSOLU","LIVE EXAROTON CONSOLE"},{"ONLINE OYUNCULAR","ONLINE PLAYERS"},{"HIZLI KOMUTLAR","QUICK COMMANDS"},{"YEREL SUNUCU","LOCAL SERVER"},{"OTOMATİK YEDEK","AUTOMATIC BACKUP"},{"Çoklu Sunucu Yönetim Merkezi","Multi-Server Management Center"},{"AeroGuard V2.3 Aktif","AeroGuard V2.3 Active"},{"Sunucu kapalı","Server offline"},{"Sunucu online","Server online"},{"Sunucu başlatılıyor...","Server is starting..."},{"Yedek alınıyor...","Creating backup..."},{"Yedek hazır","Backup ready"},{"Gündüz yap","Set daytime"},{"Havayı temizle","Clear weather"},{"Dünyayı kaydet","Save world"},{"Oyuncuları yenile","Refresh players"},{"Yayınla","Broadcast"},{"Herkese mesaj","Message everyone"},{"Planlı yedek: Kapalı","Scheduled backup: Off"},{"Her 15 dakika","Every 15 minutes"},{"Her 30 dakika","Every 30 minutes"},{"Her 60 dakika","Every 60 minutes"},{"server.jar dosyasını seç","Select the server.jar file"},{"Konsol komutu yaz (örnek: say Merhaba)","Enter a console command (example: say Hello)"},{"Online oyuncu yok","No players online"},
            {"Sağlayıcı","Provider"},{"PRO SAĞLAYICI","PRO PROVIDER"},{"Seçim bütün Pro araçlarına uygulanır","Selection applies to all Pro tools"},{"Yerel sunucu kapalı","Local server offline"},{"Yerel sunucu online","Local server online"},{"Exaroton sunucusu seçilmedi","No Exaroton server selected"},{"Sunucu seç","Select server"},{"Bağlantı bekleniyor","Waiting for connection"},{"Bağlanıyor...","Connecting..."},{"Bağlandı","Connected"},{"Bağlantı başarısız","Connection failed"},{"Ayarları Yükle","Load Settings"},{"Ayarları Kaydet","Save Settings"},{"OYUNCU YÖNETİMİ","PLAYER MANAGEMENT"},{"YÖNETİM GÜNLÜĞÜ","MANAGEMENT LOG"},{"Oyuncu adı","Player name"},{"Sebep veya mesaj (isteğe bağlı)","Reason or message (optional)"},{"OP Ver","Grant OP"},{"OP Al","Revoke OP"},{"Unban","Unban"},{"Özel Mesaj","Private Message"},{"PvP açık","PvP enabled"},{"Whitelist açık","Whitelist enabled"},{"Maksimum oyuncu","Maximum players"},{"Oyun modu","Game mode"},{"Zorluk","Difficulty"},{"Sunucu açıklaması (MOTD)","Server description (MOTD)"},{"Henüz yönetim işlemi yapılmadı","No management action yet"},{"Bazı server.properties değişiklikleri sunucu yeniden başlatıldıktan sonra uygulanır.","Some server.properties changes apply after restarting the server."},
            {"SUNUCU RAM","SERVER RAM"},{"ÇALIŞMA / DURUM","UPTIME / STATUS"},{"OYUNCULAR","PLAYERS"},{"CANLI PERFORMANS","LIVE PERFORMANCE"},{"AKILLI LOG ANALİZCİSİ","SMART LOG ANALYZER"},{"Kritik konsol satırlarını Türkçe çözümlerle açıklar.","Explains critical console lines with actionable solutions."},{"Henüz önemli bir hata yakalanmadı","No important error detected yet"},{"Analizi Temizle","Clear Analysis"},{"GÜVENLİ DOSYA YÖNETİCİSİ","SAFE FILE MANAGER"},{"Dosya seç","Select file"},{"Klasörü Aç","Open Folder"},{"Güvenlik için yalnızca temel sunucu yapılandırma dosyaları düzenlenebilir. Kaydetmeden önce otomatik .bak kopyası alınır.","For safety, only core server configuration files can be edited. An automatic .bak copy is created before saving."},{"EKLENTİ VE MOD YÖNETİCİSİ","PLUGIN AND MOD MANAGER"},{"Eklentiler (plugins)","Plugins"},{"Modlar (mods)","Mods"},{"Dosya Ekle","Add File"},{"Etkinleştir / Devre Dışı","Enable / Disable"},{"JAR dosyaları sunucu klasörüne kopyalanır. Değişikliklerin uygulanması için sunucuyu yeniden başlat.","JAR files are copied to the server folder. Restart the server to apply changes."},{"DÜNYA YÖNETİMİ","WORLD MANAGEMENT"},{"Dünyaları Yedekle","Back Up Worlds"},{"Seçileni Geri Yükle","Restore Selected"},{"Yeni dünya adı","New world name"},{"Yeni Dünyayı Ayarla","Set New World"},{"Geri yükleme sadece sunucu kapalıyken yapılır; mevcut dünya silinmez, tarihli bir kurtarma klasörüne taşınır.","Restore is available only while the server is offline; the current world is moved to a dated recovery folder."},
            {"GÖREV ZAMANLAYICISI","TASK SCHEDULER"},{"TEK SEFERLİK GÖREV ZAMANLAYICISI","ONE-TIME TASK SCHEDULER"},{"OTOMASYON KAPSAMI","AUTOMATION SCOPE"},{"YEREL SUNUCU KORUMASI","LOCAL SERVER PROTECTION"},{"BİLDİRİMLER","NOTIFICATIONS"},{"DISCORD BİLDİRİM MERKEZİ","DISCORD NOTIFICATION CENTER"},{"BAKIM MODU","MAINTENANCE MODE"},{"Exaroton Otomasyon Merkezini Aç","Open Exaroton Automation Center"},{"Görevi Planla","Schedule Task"},{"Seçili Görevi Sil","Delete Selected Task"},{"dakika sonra","minutes later"},{"Duyuru metni","Announcement text"},{"OLAY KURALLARI & DISCORD","EVENT RULES & DISCORD"},{"Çökünce otomatik yeniden başlat","Restart automatically after a crash"},{"Yerel sunucu çökerse otomatik yeniden başlat","Restart the local server automatically after a crash"},{"Yüksek RAM kullanımında bildir","Notify on high RAM usage"},{"RAM sınırı (MB)","RAM threshold (MB)"},{"Discord bildirimleri açık","Discord notifications enabled"},{"Açılma / kapanma","Start / stop"},{"Çökme ve kritik hata","Crashes and critical errors"},{"Oyuncu girişleri","Player joins"},{"RAM ve Kriz Modu","RAM and Crisis Mode"},{"Bakım ve yedek","Maintenance and backups"},{"Zamanlanmış görevler","Scheduled tasks"},{"Kritik olayda rolü etiketle","Mention role for critical events"},{"Discord rol kimliği","Discord role ID"},{"Webhook görünen adı","Webhook display name"},{"Şifreli Sakla","Store Encrypted"},{"Kayıtlı Webhook'u Aç","Unlock Saved Webhook"},{"Test Mesajı","Test Message"},{"BAKIM MODUNU BAŞLAT","START MAINTENANCE MODE"},{"Whitelist açılır, oyuncular bilgilendirilir, dünya kaydedilir, yedek alınır ve sunucu güvenli şekilde kapatılır.","Enables the whitelist, informs players, saves and backs up the world, then safely stops the server."},{"OYUNCU PROFİLLERİ","PLAYER PROFILES"},{"İlk Giriş","First Join"},{"Son Görülme","Last Seen"},{"Giriş","Joins"},{"Oyun Süresi","Play Time"},{"Geçmişi Temizle","Clear History"},{"Canlı veri bekleniyor","Waiting for live data"},
            {"CANLI OYUNCU HARİTASI","LIVE PLAYER MAP"},{"HARİTADAKİ OYUNCULAR","PLAYERS ON MAP"},{"Boyut","Dimension"},{"Oyuncuları otomatik ortala","Auto-center players"},{"Hareket izlerini göster","Show movement trails"},{"Haritayı Ortala","Center Map"},{"Seçili Oyuncuya Git","Go to Selected Player"},{"Yakınlığı Sıfırla","Reset Zoom"},{"Fare: sürükle = kaydır, tekerlek = yakınlaştır, noktaya tıkla = seç","Mouse: drag = pan, wheel = zoom, click a dot = select"},{"Oyuncu","Player"},{"Son Veri","Last Data"},{"Yerel sunucu • canlı","Local server • live"},{"Konum sorgusu reddedildi","Position query rejected"},{"Sorgu gönderilemedi","Query could not be sent"},{"Konum sorgusu gönderilemedi","Position query could not be sent"},
            {"Bu boyutta henüz canlı oyuncu konumu alınmadı.","No live player position has been received in this dimension yet."},
            {"Görünen ad","Display name"},{"+ Favorilere Ekle","+ Add Favorite"},{"SUNUCU MERKEZİ","SERVER CENTER"},{"Durum","Status"},{"Oyuncular","Players"},{"Sürüm","Version"},{"Çalışma","Uptime"},{"Kontrol Et","Check"},{"Aternos Panelini Aç","Open Aternos Panel"},{"SUNUCU DURUMU","SERVER STATUS"},{"Gecikme","Latency"},{"Offline / erişilemiyor","Offline / unreachable"},
            {"TEK TIK SUNUCU KURULUM SİHİRBAZI","ONE-CLICK SERVER SETUP WIZARD"},{"HAZIR SUNUCU ŞABLONLARI","READY SERVER TEMPLATES"},{"Yeni sunucu klasörünü seç","Choose a new server folder"},{"Minecraft sürümü","Minecraft version"},{"Şablon","Template"},{"Minecraft EULA koşullarını okudum ve kabul ediyorum","I have read and accept the Minecraft EULA"},{"Güncel Minecraft EULA'sını Aç ↗","Open the Current Minecraft EULA ↗"},{"Minecraft Kullanım Kurallarını Aç ↗","Open the Minecraft Usage Guidelines ↗"},{"EULA metni AeroMC içine kopyalanmaz; yukarıdaki resmî ve güncel Minecraft sayfasından okunur. Onay kutusu yalnızca sen işaretlediğinde eula.txt oluşturulur. İndirmeler resmî PaperMC, Fabric veya Mojang kaynaklarından yapılır.","The EULA text is not copied into AeroMC; read it on the official current Minecraft page above. The eula.txt file is created only after you select the checkbox. Downloads use official PaperMC, Fabric, or Mojang sources."},{"SUNUCUYU HAZIRLA","PREPARE SERVER"},{"EKLENTİ / MOD UYUMLULUK KONTROLÜ","PLUGIN / MOD COMPATIBILITY CHECK"},{"UYUMLULUĞU TARA","SCAN COMPATIBILITY"},{"Dosya","File"},{"Tür","Type"},{"Açıklama","Description"},{"GELİŞMİŞ YEDEK MERKEZİ","ADVANCED BACKUP CENTER"},{"Yeni Yedek","New Backup"},{"Not Ekle","Add Note"},{"Eski Yedekleri Arşivle","Archive Old Backups"},{"Son","Keep last"},{"yedek kalsın","backups"},{"AKILLI OPTİMİZASYON ASİSTANI","SMART OPTIMIZATION ASSISTANT"},{"AYARLARI ANALİZ ET","ANALYZE SETTINGS"},{"Güvenli Önerileri Uygula","Apply Safe Recommendations"},{"ROL TABANLI UZAKTAN ERİŞİM","ROLE-BASED REMOTE ACCESS"},{"GÜVENLİK MERKEZİ & İŞLEM GÜNLÜĞÜ","SECURITY CENTER & AUDIT LOG"},{"Kullanıcı adı","Username"},{"En az 10 karakterli parola","Password with at least 10 characters"},{"Kullanıcı Oluştur","Create User"},{"Yerel ağdaki telefonlara aç","Allow phones on the local network"},{"Uzaktan Erişimi Başlat","Start Remote Access"},{"Tarayıcıda Aç","Open in Browser"},{"Güvenlik Günlüğünü Yenile","Refresh Security Log"},{"Dili Uygula","Apply Language"},{"DİL & GÖRÜNÜM","LANGUAGE & APPEARANCE"},{"DİL & ARAYÜZ","LANGUAGE & INTERFACE"},{"ARAYÜZ DÜZENİ","INTERFACE ORGANIZATION"},{"PERFORMANS ÖZELLİKLERİ","PERFORMANCE FEATURES"},{"Canlı Harita özelliğini etkinleştir","Enable Live Map feature"},{"Türkçe","Turkish"},{"İngilizce","English"},
            {"Spark'ı da ekle (önerilir)","Also add Spark (recommended)"},{"Paper 1.21 ve üzeri Spark profiler'ı zaten içinde getirir; ayrıca indirmeye gerek yok.","Paper 1.21 and newer already bundle the Spark profiler; no separate download is needed."},{"Vanilla sunucu eklenti/mod yükleyemediği için Spark otomatik eklenemez.","Spark cannot be added automatically because a Vanilla server cannot load plugins or mods."},{"Spark hızlı ekleme, 1.21 öncesi Paper ve Fabric kurulumlarında gösterilir.","Quick Spark setup is available for Paper and Fabric versions before 1.21."},{"Seçersen AeroMC uyumlu Spark JAR'ını doğrulayıp plugins klasörüne koyar.","If selected, AeroMC verifies a compatible Spark JAR and places it in the plugins directory."},{"Seçersen AeroMC uyumlu Spark JAR'ını doğrulayıp mods klasörüne koyar.","If selected, AeroMC verifies a compatible Spark JAR and places it in the mods directory."},
            {"Arayüz dili anında değiştirilir ve sonraki açılış için saklanır.","The interface language changes instantly and is saved for the next launch."},{"Kapatıldığında Canlı Harita sekmesiyle birlikte konum sorguları, çizim zamanlayıcısı ve Exaroton harita dinleyicileri tamamen durdurulur. Değişiklik anında uygulanır.","When disabled, the Live Map tab, position queries, drawing timer, and Exaroton map listeners stop completely. The change applies immediately."},{"Sunucu işlemleri Sunucular'da, oyuncu ve yapılandırma işlemleri Yönetim'de, tanılama araçları Kontrol Merkezi'nde, kurulum ve bakım araçları ise Araçlar'da bulunur.","Server actions are under Servers, player and configuration actions under Management, diagnostics under Control Center, and setup and maintenance under Tools."},
            {"Bütün ana ekranlar, düğmeler, alan ipuçları ve değişen durum metinleri anında çevrilir; seçim sonraki açılışta korunur.","All main screens, buttons, field hints, and changing status text are translated instantly; the choice is saved for the next launch."},{"Kapatıldığında harita sekmesi, 5 saniyelik konum sorguları, çizim zamanlayıcısı ve Exaroton konsol dinleyicileri tamamen durdurulur. Değişiklik anında uygulanır.","When disabled, the map tab, 5-second position queries, drawing timer, and Exaroton console listeners stop completely. The change applies immediately."},{"İndirme yalnızca resmî PaperMC, Fabric veya Mojang sunucularından yapılır. Paper'ın yeni sürümleri daha yeni Java gerektirebilir.","Downloads use only official PaperMC, Fabric, or Mojang servers. New Paper versions may require a newer Java version."},{"JAR manifestleri, plugin.yml ve fabric.mod.json dosyaları; bozuk arşiv, yinelenen kimlik ve eksik temel bağımlılık açısından incelenir.","JAR manifests, plugin.yml, and fabric.mod.json files are checked for corrupt archives, duplicate IDs, and missing core dependencies."},{"Asistan server.properties değerlerini RAM, oyuncu sınırı, görüş ve simülasyon mesafesine göre değerlendirir. Uygulamadan önce .optimization-backup alınır.","The assistant evaluates server.properties using RAM, player limit, view distance, and simulation distance. An .optimization-backup is created before applying changes."},{"Varsayılan bağlantı yalnızca bu bilgisayara açıktır. LAN seçeneği açılırsa güçlü parola kullan. 5 hatalı girişten sonra IP adresi 60 saniye sınırlandırılır.","The default connection is available only on this computer. Use a strong password when LAN access is enabled. An IP is rate-limited for 60 seconds after 5 failed logins."},{"Favori sunucular 30 saniyede bir yenilenir. Oyuncu sayısı artınca veya sunucu kapanınca bildirim gösterilir.","Favorite servers refresh every 30 seconds. Notifications appear when the player count increases or a server goes offline."},{"Veriler panel açıkken görülen giriş/çıkışlardan ve çevrimiçi oyuncu listesinden oluşturulur.","Data is built from join/leave events and the online player list observed while the panel is running."},
            {"Onay gerekiyor","Confirmation required"},{"İşlem tamamlanamadı","Operation could not be completed"},{"Bilinmeyen hata","Unknown error"},
            {"Adres","Address"},{"Hesap","Account"},{"Kredi","Credits"},{"Konsol komutu yaz","Enter a console command"},
            {"Exaroton API anahtarı (dosyaya kaydedilmez)","Exaroton API key (not saved as plain text)"},{"Şifreleyerek sakla","Store encrypted"},{"Kayıtlı Anahtarı Aç","Unlock Saved Key"},{"Kayıtlı Anahtarı Sil","Delete Saved Key"},{"EXAROTON BAĞLANTISI","EXAROTON CONNECTION"},
            {"En az 12 karakterli parola","Password with at least 12 characters"},{"Ana Parola Oluştur","Create Master Password"},{"Ana Parolayı Gir","Enter Master Password"},{"En az 12 karakterlik bir ana parola belirle. Bu parola kaydedilmez.","Choose a master password of at least 12 characters. This password is not saved."},{"Şifreli API anahtarını açmak için ana parolanı gir.","Enter your master password to unlock the encrypted API key."},{"Ana parola","Master password"},{"Ana parolayı tekrar yaz","Enter master password again"},
            {"Durum alınıyor...","Fetching status..."},{"Durum alınamadı","Could not fetch status"},{"Sunucu bulunamadı","No servers found"},{"Sunucu başlatılıyor...","Server is starting..."},{"Sunucu durduruluyor...","Server is stopping..."},{"Sunucu yeniden başlatılıyor...","Server is restarting..."},{"Komut gönderiliyor...","Sending command..."},
            {"Durumu Kontrol Et","Check Status"},{"Aternos Resmî Panelini Aç ↗","Open Official Aternos Panel ↗"},{"ATERNOS SUNUCU DURUMU","ATERNOS SERVER STATUS"},{"Sunucu adresi: örnek.aternos.me","Server address: example.aternos.me"},{"Aternos resmî bir yönetim API'si sunmadığı için bu sekme yalnızca herkese açık sunucu durumunu okur. Başlatma, durdurma ve yedekleme işlemleri resmî Aternos panelinde yapılır.","Because Aternos does not provide an official management API, this tab only reads the public server status. Start, stop, and backup operations are handled in the official Aternos panel."},{"Aternos paneli tarayıcıda açıldı","Aternos panel opened in the browser"},{"Aternos paneli açılamadı","Could not open the Aternos panel"},{"Tarayıcı açılamadı. Adresi elle açabilirsin:\nhttps://aternos.org/server/","The browser could not be opened. You can open this address manually:\nhttps://aternos.org/server/"},
            {"Yedek al","Create backup"},{"Yeniden başlat","Restart"},{"Sunucuyu durdur","Stop server"},{"Duyuru gönder","Send announcement"},{"SkyBlock Temeli","SkyBlock Starter"},{"Modlu Sunucu","Modded Server"},
            {"Sunucular","Servers"},{"Kontrol Merkezi","Control Center"},{"AKTİF SUNUCU","ACTIVE SERVER"},{"Sunucu Sağlığı","Server Health"},{"Eklenti & Modlar","Plugins & Mods"},{"Başarı Kartları","Achievement Cards"},
            {"SUNUCU SAĞLIK PUANI","SERVER HEALTH SCORE"},{"GECİKME","LATENCY"},{"Canlı ölçüm bekleniyor","Waiting for live metrics"},{"Mükemmel","Excellent"},{"Sağlıklı","Healthy"},{"Dikkat","Caution"},{"Riskli","At Risk"},{"Kritik","Critical"},
            {"KRİZ MODU","CRISIS MODE"},{"Kriz Modu beklemede","Crisis Mode standing by"},{"Kriz Modunu otomatik tetikle","Trigger Crisis Mode automatically"},{"TPS altı","TPS below"},{"RAM %","RAM %"},{"Tetikleme (sn)","Trigger (sec)"},{"Toparlanma (sn)","Recovery (sec)"},{"Yeniden tetikleme beklemesi (sn)","Retrigger cooldown (sec)"},{"Şimdi Etkinleştir","Activate Now"},{"Krizden Çık","Exit Crisis Mode"},{"Akıllı Eşik Öner","Suggest Smart Thresholds"},{"Öneri için sunucuyu bir süre normal kullan","Use the server normally for a while to generate a recommendation"},{"Kriz, eşiklerin belirlenen süre boyunca bozuk kalmasıyla açılır. Çıkış için TPS +1 ve RAM -%5 güvenli payla toparlanmalıdır. Manuel kriz yalnızca yönetici tarafından kapatılır; ayarlar geri yüklenmeden otomatik görevler başlamaz.","Crisis Mode starts only after thresholds remain unhealthy for the configured duration. Recovery requires a +1 TPS and -5% RAM safety margin. Manual crises only end by administrator action, and scheduled jobs stay paused until settings are restored."},
            {"KRİZ MODU GEÇMİŞİ","CRISIS MODE HISTORY"},{"Henüz Kriz Modu tetiklenmedi","Crisis Mode has not been triggered yet"},{"Son 10 tetiklenme; başlangıç zamanı, kullanılan TPS/RAM eşiği ve Kriz Modu süresiyle birlikte saklanır.","The latest 10 activations are stored with their start time, TPS/RAM thresholds, and Crisis Mode duration."},{"Yönetici tarafından etkinleştirildi","Activated by administrator"},{"Yönetici tarafından kapatıldı","Closed by administrator"},{"Sunucu değerleri kararlı biçimde toparlandı","Server metrics recovered consistently"},{"Sunucu kapandığı için koruma sonlandırıldı","Protection ended because the server stopped"},{"AeroMC kapanınca kesildi","Interrupted when AeroMC closed"},{"AeroMC kapanırken güvenle sonlandırıldı","Ended safely while AeroMC was closing"},
            {"AKILLI ÇÖKME DOKTORU","SMART CRASH DOCTOR"},{"Konsoldaki belirtileri, olası şüpheliyi ve çözüm sırasını açıklar.","Explains console symptoms, the likely culprit, and the recommended fix order."},{"Canlı Uyarılar","Live Warnings"},{"Çökme Doktoru","Crash Doctor"},{"Henüz çökme analizi yok","No crash analysis yet"},
            {"OYUNCU BAŞARI KARTLARI","PLAYER ACHIEVEMENT CARDS"},{"Ölüm","Deaths"},{"İlerleme","Advancements"},{"OYUNCU BAŞARI KARTI","PLAYER ACHIEVEMENT CARD"},{"Kartını görmek için tablodan bir oyuncu seç.","Select a player in the table to view their card."},{"Kart Metnini Kopyala","Copy Card Text"},
            {"Taranacak sunucuyu seç","Select a server to scan"},{"JAR Seç","Choose JAR"},{"Senkronize Et","Sync Now"},{"Seçili sunucunun plugins ve mods klasörleri birlikte taranır. Sunucu değiştirildiğinde liste otomatik senkronize edilir.","The selected server's plugins and mods folders are scanned together. The list syncs automatically when the server changes."},{"Sunucu seçimi bekleniyor","Waiting for server selection"},
            {"Yedekleri gösterilecek sunucuyu seç","Select a server to view its backups"},{"Yedeği Sil","Delete Backup"},{"SUNUCUYA ÖZEL YEDEK MERKEZİ","PER-SERVER BACKUP CENTER"},{"Exaroton ve Aternos resmî API'leri dünya yedeğini indirmeye izin vermediği için burada yalnızca erişilebilen yerel sunucular gösterilir.","Because the official Exaroton and Aternos APIs do not allow world-backup downloads, only accessible local servers are shown here."},
            {"1 • UZAKTAN ERİŞİM KULLANICISI OLUŞTUR","1 • CREATE A REMOTE ACCESS USER"},{"2 • BAĞLANTIYI BAŞLAT","2 • START THE CONNECTION"},{"3 • GÜVENLİK GÜNLÜĞÜ","3 • SECURITY LOG"},{"Adresi Kopyala","Copy Address"},{"Açılacak adres:","Address to open:"},{"Uzaktan erişim kapalı","Remote access is off"},{"Günlüğü Yenile","Refresh Log"},{"Günlüğü Temizle","Clear Log"},{"Zaman","Time"},{"Kullanıcı","User"},{"Olay","Event"},{"Hedef","Target"},{"Sonuç","Result"},
            {"VIEWER: yalnızca durumu görür  •  MODERATOR: mesaj, kick ve ban kullanır  •  ADMIN: başlatma, durdurma, yedek ve konsol dahil tam yetkilidir.","VIEWER: status only  •  MODERATOR: messages, kick, and ban  •  ADMIN: full access including start, stop, backup, and console."},{"Aynı bilgisayar: LAN kutusunu işaretleme ve Tarayıcıda Aç'a bas.  •  Telefon/başka bilgisayar: LAN kutusunu aç, cihazı aynı Wi-Fi'a bağla ve aşağıdaki adresi yaz.","Same computer: leave LAN unchecked and press Open in Browser.  •  Phone/another computer: enable LAN, join the same Wi-Fi, and open the address below."},{"Bu günlük; kimin giriş denediğini, hangi komutu gönderdiğini ve işlemin başarılı mı reddedilmiş mi olduğunu gösterir. Parolalar ve API anahtarları kaydedilmez. DENIED başarısız/yetkisiz giriş, RATE LIMIT ise 5 hatalı denemeden sonra geçici engel demektir.","This log shows who attempted to sign in, which command was sent, and whether it succeeded or was denied. Passwords and API keys are never recorded. DENIED means a failed/unauthorized attempt; RATE LIMIT means a temporary block after 5 failed attempts."},
            {"Tek Tık Mod Merkezi","One-Click Mod Center"},{"1 • HEDEF SUNUCU VE UYUMLULUK","1 • TARGET SERVER & COMPATIBILITY"},{"2 • MODRINTH'TE ARA","2 • SEARCH MODRINTH"},{"3 • GÜVENLİ KURULUM","3 • SAFE INSTALLATION"},{"Hedef sunucu","Target server"},{"Loader","Loader"},{"Yerel sunucuyu seç","Select local server"},{"Otomatik Algıla","Auto Detect"},{"Modrinth'te Ara","Search Modrinth"},{"Tek Tıkla Yükle","Install with One Click"},{"Proje Sayfasını Aç","Open Project Page"},{"Aternos Mod Sayfasını Aç","Open Aternos Mods Page"},{"Mod veya eklenti ara (örn. voice chat)","Search for a mod or plugin (e.g. voice chat)"},{"Örn. 1.20.4","E.g. 1.20.4"},{"Sunucu ve yazılım bilgisi bekleniyor","Waiting for server and software details"},{"Arama sonuçlarından bir proje seç.","Select a project from the search results."},{"Yalnız sunucu uyumlu sonuçlar gösterilir. Zorunlu bağımlılıklar otomatik çözülür ve her dosya SHA-512 ile doğrulanır. Yerel kurulumdan önce mods/plugins yedeği alınır.","Only server-compatible results are shown. Required dependencies are resolved automatically and every file is verified with SHA-512. The mods/plugins folder is backed up before a local installation."},
            {"Aternos otomatik dosya yükleme API'si sunmuyor. Sürüm ve loader'ı seç; proje bulunduktan sonra Aternos mod sayfasında aynı adı arat.","Aternos does not provide an automatic file-upload API. Select the version and loader, then search for the same project name on the Aternos mods page."},{"Aternos için Minecraft sürümünü ve loader'ı elle seç.","Select the Minecraft version and loader manually for Aternos."},{"Önce Sunucular bölümünden bir JAR seç veya Araçlar → Kurulum ile sunucu kur.","First choose a JAR in Servers or install a server under Tools → Setup."},{"Önce Sunucular → Exaroton bölümünden bir sunucu seç.","First select a server under Servers → Exaroton."},{"Exaroton yazılım bilgisi alınıyor...","Fetching Exaroton software details..."},
            {"Arama için en az 2 karakter yaz.","Enter at least 2 characters to search."},{"Minecraft sürümü ve loader seçimi gerekli.","Minecraft version and loader are required."},{"Vanilla sunucu mod/eklenti yükleyemez. Fabric, Forge, NeoForge veya eklenti destekli bir yazılım seç.","A Vanilla server cannot load mods or plugins. Select Fabric, Forge, NeoForge, or plugin-compatible server software."},{"Modrinth aranıyor...","Searching Modrinth..."},{"Bu sürüm ve loader için sunucu uyumlu sonuç bulunamadı.","No server-compatible result was found for this version and loader."},{"Arama başarısız","Search failed"},
            {"Önce bir proje seç.","Select a project first."},{"Yüklenecek yerel sunucuyu seç.","Select the local target server."},{"Önce Exaroton sunucusunu seç.","Select an Exaroton server first."},{"Exaroton resmî API'si dosya yüklemeye izin verir fakat uzaktaki mevcut mods/plugins klasörünü panel içine yedekleyemez. Devam edilsin mi?","The official Exaroton API allows file uploads, but the panel cannot back up the existing remote mods/plugins folder. Continue?"},{"Kurulum başarısız • Değişiklikler mümkün olduğunca geri alındı.","Installation failed • Changes were rolled back wherever possible."},{"Kurulum tamamlandı","Installation complete"},
            {"Mod Ara & Yükle","Search & Install"},{"Güncelleme & Çakışma","Updates & Conflicts"},{"AKILLI MOD GÜNCELLEME MERKEZİ","SMART MOD UPDATE CENTER"},{"ÇAKIŞMA DEDEKTÖRÜ","CONFLICT DETECTOR"},{"Güncellemeleri ve Çakışmaları Tara","Scan Updates & Conflicts"},{"Tüm Güncellemeleri Seç","Select All Updates"},{"Seçilenleri Güvenle Güncelle","Safely Update Selected"},{"Güncelleme taraması bekleniyor","Waiting for an update scan"},{"Ayar değişti • yeniden tarama gerekli","Settings changed • scan again"},{"Kurulu JAR'lar SHA-512 ile tanınır. Yalnızca seçili Minecraft sürümü ve loader ile uyumlu güncellemeler sunulur; uygulamadan önce yedek ve kesin bağımlılık çözümü yapılır.","Installed JARs are identified by SHA-512. Only updates compatible with the selected Minecraft version and loader are offered; a backup and exact dependency resolution run before changes are applied."},
            {"Güncelleme taraması için geçerli Minecraft sürümü ve loader gerekli.","A valid Minecraft version and loader are required for an update scan."},{"Aternos otomatik dosya inceleme API'si sunmadığı için güncellemeler resmî panelden yönetilir.","Aternos does not provide an automatic file-inspection API, so updates are managed from its official panel."},{"Taranacak yerel sunucuyu seç.","Select the local server to scan."},{"Kurulu JAR'lar tanınıyor ve uyumluluk inceleniyor...","Identifying installed JARs and checking compatibility..."},{"Güncelleme taraması başarısız","Update scan failed"},{"Önce güncelleme ve çakışma taraması yap.","Run an update and conflict scan first."},{"Güncellenecek en az bir proje seç.","Select at least one project to update."},{"Kritik çakışmalar çözülmeden otomatik güncelleme yapılmadı. Çakışma Dedektörü'ndeki kırmızı maddeleri kontrol et.","Automatic updates were blocked until critical conflicts are resolved. Check the red items in Conflict Detector."},{"Modları güncellemeden önce yerel sunucuyu durdur.","Stop the local server before updating mods."},{"Kesin bağımlılıklar çözülüyor ve güvenli güncelleme hazırlanıyor...","Resolving exact dependencies and preparing a safe update..."},{"Güncelleme başarısız • geri alma koruması çalıştı","Update failed • rollback protection was activated"},{"Güncelleme tamamlandı","Update complete"},{"Exaroton modlarını güncellemeden önce sunucuyu durdur.","Stop the Exaroton server before updating mods."}
        });
        putAll(new String[][]{
            {"GÜVENLİ KİMLİK BİLGİLERİ", "SECURE CREDENTIALS"},
            {"Exaroton, Pterodactyl ve Discord kimlik bilgilerini bu cihazda otomatik aç", "Automatically unlock Exaroton, Pterodactyl, and Discord credentials on this device"},
            {"Bu cihazın güvenli kasasından otomatik kullanılıyor", "Automatically supplied by this device's secure vault"},
            {"PTERODACTYL BAĞLANTISI", "PTERODACTYL CONNECTION"},
            {"Pterodactyl sunucusu seç", "Select a Pterodactyl server"},
            {"Güvenli Kasayla Bağlan", "Connect with Secure Vault"},
            {"Kasa Kaydını Sil", "Delete Vault Entry"},
            {"Panelde Aç", "Open in Panel"},
            {"SUNUCU KONTROLÜ", "SERVER CONTROL"},
            {"PTERODACTYL İŞLEM GÜNLÜĞÜ", "PTERODACTYL ACTIVITY LOG"},
            {"CANLI PTERODACTYL KONSOLU", "LIVE PTERODACTYL CONSOLE"},
            {"Komutlar Client API ile gönderilir; canlı çıktı ve performans verileri Pterodactyl'in kısa ömürlü WebSocket biletiyle alınır. API anahtarı WebSocket bağlantısına gönderilmez.", "Commands are sent through the Client API; live output and performance data use Pterodactyl's short-lived WebSocket ticket. The API key is never sent to the WebSocket connection."},
            {"Zorla Kapat", "Force Kill"},
            {"DİSK", "DISK"},
            {"ÇALIŞMA", "UPTIME"},
            {"Askıya alınmış", "Suspended"},
            {"Başlatılıyor", "Starting"},
            {"Çalışıyor", "Running"},
            {"Durduruluyor", "Stopping"},
            {"API anahtarını bir kez gir; başarılı bağlantıda otomatik saklanır", "Enter the API key once; it will be saved after a successful connection"},
            {"Webhook'u bir kez gir; otomatik kasaya kaydedilir", "Enter the webhook once; it will be saved in the automatic vault"},
            {"EXAROTON BAŞLATMA", "EXAROTON STARTUP"},
            {"Exaroton sunucusunu başlatmadan önce hazırlık denetimi yap", "Run readiness check before starting an Exaroton server"},
            {"Denetimsiz Başlat", "Start Without Check"},
            {"Denetim zaman aşımına uğradı", "Readiness check timed out"},
            {"AEROMC GÜNCELLEME MERKEZİ", "AEROMC UPDATE CENTER"},
            {"KURULU SÜRÜM", "INSTALLED VERSION"},
            {"SON YAYIN", "LATEST RELEASE"},
            {"Kanal", "Channel"},
            {"Kararlı", "Stable"},
            {"Beta", "Beta"},
            {"AeroMC açıldığında güncellemeleri kontrol et", "Check for updates when AeroMC starts"},
            {"Güncellemeyi Kontrol Et", "Check for Updates"},
            {"İndir ve Kur", "Download and Install"},
            {"GitHub Sürümünü Aç", "Open GitHub Release"},
            {"Sürüm notları burada gösterilecek", "Release notes will appear here"},
            {"TEK TIK LAG ANALİZİ", "ONE-CLICK LAG ANALYSIS"},
            {"Analiz süresi", "Analysis duration"},
            {"Hızlı • 60 saniye", "Quick • 60 seconds"},
            {"Normal • 3 dakika", "Normal • 3 minutes"},
            {"Detaylı • 5 dakika", "Detailed • 5 minutes"},
            {"LAG ANALİZİNİ BAŞLAT", "START LAG ANALYSIS"},
            {"HAZIR RAPORU AÇ", "OPEN READY REPORT"},
            {"Spark Yoksa?", "No Spark?"},
            {"1. Sunucuyu aç  •  2. Süreyi seç  •  3. Analizi başlat", "1. Start the server  •  2. Choose a duration  •  3. Start the analysis"},
            {"İki ölçümlü rapordan sonra TPS değişimi burada görünecek", "TPS change will appear here after two measured reports"},
            {"Sunucu kasarken başlat ve hiçbir şey yapmadan geri sayımın bitmesini bekle. AeroMC rapor bağlantısını konsoldan kendisi yakalar; hazır olduğunda yalnızca 'Hazır Raporu Aç'a basarsın.", "Start it while the server is lagging and wait for the countdown to finish. AeroMC captures the report link from the console automatically; when ready, simply press 'Open Ready Report'."},
            {"BİLDİRİM MERKEZİ", "NOTIFICATION CENTER"},
            {"Tümü", "All"}, {"Okunmamış", "Unread"}, {"Uyarı", "Warning"}, {"Başarılı", "Success"}, {"Bilgi", "Info"},
            {" okunmamış", " unread"}, {"Henüz önemli bir bildirim yok", "No important notifications yet"},
            {"Tümünü Okundu Yap", "Mark All as Read"}, {"Bildirim geçmişinin tamamı silinsin mi?", "Delete the entire notification history?"},
            {"Bildirim geçmişini temizle", "Clear notification history"}, {"Kısa Özellik Turunu Aç", "Open Quick Feature Tour"},
            {"Bildirimler açık", "Notifications enabled"}, {"Bildirim Sunucuları", "Notification Servers"}, {"Paneli Daralt", "Collapse Panel"}, {"Paneli Genişlet", "Expand Panel"},
            {"Henüz sunucu kaynağı yok", "No server source yet"}, {"Favori", "Favorite"},
            {"Online durumu doğrulanıyor...", "Verifying online status..."}, {"Bağlantı yeniden doğrulanıyor...", "Rechecking connection..."},
            {"Kurallar & Sessiz Saatler", "Rules & Quiet Hours"}, {"Deneme Bildirimi", "Test Notification"},
            {"Bildirim Kuralları & Sessiz Saatler", "Notification Rules & Quiet Hours"}, {"Her sunucudan hangi olayların gelebileceğini seç", "Choose which events can arrive from each server"},
            {"Bu sunucudan bildirim al", "Receive notifications from this server"}, {"Açılma", "Startup"}, {"Kapanma", "Shutdown"}, {"Oyuncu", "Player"}, {"Çökme", "Crash"}, {"RAM / Kriz / Lag", "RAM / Crisis / Lag"}, {"Yedek", "Backup"},
            {"SUNUCU BAZLI KURALLAR", "PER-SERVER RULES"}, {"SESSİZ SAATLER & TEKRAR KORUMASI", "QUIET HOURS & REPEAT PROTECTION"},
            {"Sessiz saatleri etkinleştir", "Enable quiet hours"}, {"Başlangıç", "Start"}, {"Bitiş", "End"}, {"Aynı uyarı beklemesi (sn)", "Same-alert cooldown (sec)"}, {"Kuralları Kaydet", "Save Rules"},
            {"AeroMC Kısa Özellik Turu", "AeroMC Quick Feature Tour"}, {"Turu Geç", "Skip Tour"}, {"Geri", "Back"}, {"İleri", "Next"}, {"Turu Bitir", "Finish Tour"}, {"Adım", "Step"},
            {"AEROMC'YE HOŞ GELDİN", "WELCOME TO AEROMC"}, {"Bütün sunucuların tek merkezde", "All your servers in one place"},
            {"Yerel JAR, Exaroton, Aternos ve Pterodactyl sunucularını Sunucular bölümünden yönetebilirsin. Ana Panel ise favorilerini ve önemli bildirimlerini tek bakışta gösterir.", "Manage Local JAR, Exaroton, Aternos, and Pterodactyl servers under Servers. The Dashboard shows favorites and important notifications at a glance."},
            {"SUNUCUNU KORU", "PROTECT YOUR SERVER"}, {"Sorunu büyümeden yakala", "Catch issues before they grow"},
            {"Kontrol Merkezi; sağlık puanı, Kriz Modu, Çökme Doktoru ve Tek Tık Lag Analizi ile performans sorunlarını anlaşılır biçimde açıklar.", "Control Center explains performance issues clearly with Health Score, Crisis Mode, Crash Doctor, and One-Click Lag Analysis."},
            {"İŞLERİ OTOMATİKLEŞTİR", "AUTOMATE THE WORK"}, {"Yedek, görev ve kredi koruması", "Backups, tasks, and credit protection"},
            {"Planlı yedekler, Exaroton programları, oyuncusuz durdurma ve kredi eşikleri gereksiz masrafı ve unutulan işleri azaltır.", "Scheduled backups, Exaroton schedules, idle stopping, and credit thresholds reduce unnecessary cost and forgotten tasks."},
            {"HER ŞEY HAZIR", "YOU'RE ALL SET"}, {"Önemli olaylar artık kaybolmaz", "Important events no longer get lost"},
            {"Ana Panel'deki Bildirim Merkezi çökme, yedek, güncelleme, oyuncu ve otomasyon olaylarını saklar. Bu turu Ayarlar → Dil & Arayüz bölümünden tekrar açabilirsin.", "The Notification Center on the Dashboard keeps crash, backup, update, player, and automation events. You can reopen this tour under Settings → Language & Interface."},
            {"AEROMC GÜVENLİK KALKANI", "AEROMC SECURITY SHIELD"}, {"Güvenlik taraması bekleniyor", "Waiting for a security scan"}, {"Henüz güvenlik bulgusu yok", "No security findings yet"},
            {"Güvenliği Tara", "Scan Security"}, {"Dosya İzinlerini Güçlendir", "Harden File Permissions"}, {"Güçlü", "Strong"}, {"İyi", "Good"},
            {"Tarama yalnızca yerel ayarları ve izinleri okur. Güçlendirme; AeroMC veri klasörünü 700, hassas dosyaları 600 iznine çeker. Windows ve macOS'ta desteklenmeyen POSIX izinleri değiştirilmez.", "The scan only reads local settings and permissions. Hardening sets the AeroMC data directory to 700 and sensitive files to 600. Unsupported POSIX permissions are left unchanged on Windows and macOS."},
            {"Kritik konsol komutunu doğrula", "Confirm Critical Console Command"}, {"Konsol komutunu doğrula", "Confirm Console Command"}
            ,{"Sunucu Kontrolü", "Server Control"}, {"Filo Paneli", "Fleet Panel"}, {"Kredi Koruması", "Credit Guard"}, {"Otomasyon Merkezi", "Automation Center"}
            ,{"PTERODACTYL BAĞLANTISI", "PTERODACTYL CONNECTION"}, {"Pterodactyl Client API anahtarı (ptlc_...)", "Pterodactyl Client API key (ptlc_...)"}, {"Güvenli Kasayla Bağlan", "Connect with Secure Vault"}, {"Kasa Kaydını Sil", "Delete Vault Entry"}, {"Pterodactyl sunucusu seç", "Select a Pterodactyl server"}, {"Panelde Aç", "Open in Panel"}, {"DURUM", "STATUS"}, {"DİSK", "DISK"}, {"ÇALIŞMA", "UPTIME"}, {"CANLI PTERODACTYL KONSOLU", "LIVE PTERODACTYL CONSOLE"}
            ,{"Yalnız Client API anahtarı kullan. AeroMC yönlendirmeleri izlemez; uzak panellerde HTTPS zorunludur. Anahtar başarılı bağlantıdan sonra görünür alandan temizlenir ve otomatik kasa açıksa cihaz bağlı AES-256-GCM kasasına alınır.", "Use only a Client API key. AeroMC does not follow redirects; HTTPS is required for remote panels. After a successful connection the key is cleared from the visible field and, when the automatic vault is enabled, stored in this device-bound AES-256-GCM vault."}
            ,{"Komutlar Client API ile gönderilir; canlı çıktı ve performans verileri Pterodactyl'in kısa ömürlü WebSocket biletiyle alınır. API anahtarı WebSocket bağlantısına gönderilmez.", "Commands are sent through the Client API; live output and performance data use Pterodactyl's short-lived WebSocket token. The API key is never sent over the WebSocket connection."}
            ,{"Pterodactyl sunucusu seçilmedi", "No Pterodactyl server selected"}, {"Bağlandı • erişilebilir sunucu yok", "Connected • no accessible servers"}, {"Güvenli Pterodactyl kasası açılıyor...", "Opening secure Pterodactyl vault..."}, {"Pterodactyl kasası açılamadı", "Could not open the Pterodactyl vault"}, {"Pterodactyl paneline bağlanılıyor...", "Connecting to Pterodactyl panel..."}
            ,{"ATERNOS SUNUCU DURUMU", "ATERNOS SERVER STATUS"}, {"Sunucu adresi: örnek.aternos.me veya adres:port", "Server address: example.aternos.me or address:port"}, {"Son kontrol", "Last checked"}, {"Adres her 15 saniyede bir yenilenir. Aternos resmî bir yönetim API'si sunmadığı için panel, herkese açık Minecraft durum bilgisini okur; başlatma/durdurma gibi ayrıntılı Aternos durumları resmî panelden yönetilir.", "The address refreshes every 15 seconds. Because Aternos does not provide an official management API, this panel reads public Minecraft status information; detailed Aternos actions such as start and stop are managed in the official panel."}
            ,{"EXAROTON FİLO ÖZETİ", "EXAROTON FLEET OVERVIEW"}, {"Tümünü Yenile", "Refresh All"}, {"Oyuncusuz Online Sunucuları Durdur", "Stop Empty Online Servers"}, {"Toplam saatlik maliyet, online sunucuların ayrılmış RAM miktarından hesaplanır. Toplu durdurma yalnızca oyuncu sayısı sıfır görünen online sunuculara uygulanır ve önce onay ister.", "The total hourly cost is calculated from RAM allocated to online servers. Bulk stop applies only to online servers that show zero players and asks for confirmation first."}
            ,{"OTOMASYON ANA KONTROLÜ", "AUTOMATION MAIN CONTROL"}, {"Hedef sunucu bağlanmadı", "No target server connected"}, {"Tüm Exaroton otomasyonları açık", "Enable all Exaroton automations"}, {"Seçili Sunucuyu Hedefle", "Target Selected Server"}, {"Şimdi Denetle", "Check Now"}, {"Tümünü Kapat", "Disable All"}, {"Tüm otomasyonlar kapalı", "All automations are disabled"}, {"Hazır olma takibi beklemede", "Readiness monitoring is standing by"}
            ,{"HAFTA İÇİ & HAFTA SONU PROGRAMI", "WEEKDAY & WEEKEND SCHEDULE"}, {"Saat programı açık", "Enable schedule"}, {"Hafta içi", "Weekdays"}, {"Hafta sonu", "Weekends"}, {"Gece yarısını aşan programlar desteklenir. Örnek: 20:00 → 02:00. Zamanlama ve otomatik eylemler AeroMC açıkken çalışır.", "Schedules that cross midnight are supported. Example: 20:00 → 02:00. Scheduling and automatic actions run while AeroMC is open."}
            ,{"ÇÖKME KURTARMA & OYUNCU BEKLEME", "CRASH RECOVERY & IDLE STOP"}, {"Çökerse otomatik kurtar", "Recover automatically after a crash"}, {"En fazla deneme", "Maximum attempts"}, {"Oyuncu gelmezse durdur", "Stop when no players arrive"}, {"Oyuncusuz dakika", "Minutes without players"}
            ,{"GÜNLÜK & HAFTALIK KREDİ BÜTÇESİ", "DAILY & WEEKLY CREDIT BUDGET"}, {"Günlük bütçe", "Daily budget"}, {"Haftalık bütçe", "Weekly budget"}, {"Bütçe verisi bekleniyor", "Waiting for budget data"}, {"Bütçe sınırı en yüksek önceliktedir; sınır dolunca sunucu oyuncu olsa da duyuru gönderilerek durdurulur ve yeniden başlatılmaz. Her otomatik işlemden hemen önce sunucu durumu tekrar doğrulanır.", "The budget limit has highest priority; when reached, the server is stopped with an announcement even if players are online, and it will not restart. The server state is verified again immediately before every automatic action."}
            ,{"EXAROTON OLAY GÜNLÜĞÜ", "EXAROTON EVENT LOG"}, {"Günlüğü Yenile", "Refresh Log"}, {"Günlüğü Temizle", "Clear Log"}, {"Henüz Exaroton otomasyon olayı yok", "No Exaroton automation events yet"}
            ,{"API anahtarını şifreli sakla", "Store API key encrypted"}, {"Kayıtlı Anahtarla Bağlan", "Connect with Saved Key"}, {"Kaydı Sil", "Delete Entry"}, {"Hazırlık Denetimi", "Readiness Check"}, {"Konsol komutu yaz", "Enter a console command"}
            ,{"MEVCUT KREDİ", "CURRENT CREDITS"}, {"BUGÜN HESAPTAN HARCANAN", "SPENT FROM ACCOUNT TODAY"}, {"SEÇİLİ SUNUCU / SAAT", "SELECTED SERVER / HOUR"}, {"TAHMİNİ KALAN", "ESTIMATED REMAINING"}, {"HESAP KREDİ GEÇMİŞİ", "ACCOUNT CREDIT HISTORY"}, {"DÜŞÜK KREDİ KORUMASI", "LOW-CREDIT PROTECTION"}, {"Düşük kredi eşiği açık", "Enable low-credit threshold"}, {"Eşik", "Threshold"}, {"Eşik altında sunucuyu otomatik durdur", "Automatically stop the server below threshold"}, {"Krediyi Şimdi Yenile", "Refresh Credits Now"}
            ,{"Bu bölüm yalnızca kredi bakiyesini korur. Oyuncusuz kalınca durdurma, saat programı ve çökme kurtarma ayarları Otomasyon Merkezi'nde tek yerden yönetilir. Seçili sunucu maliyeti Exaroton'un resmî 1 kredi / GiB RAM / saat tarifesine göre hesaplanır.", "This section protects only the credit balance. Idle stopping, schedules, and crash recovery are managed centrally in the Automation Center. The selected server cost is calculated using Exaroton's official rate of 1 credit / GiB RAM / hour."}
            ,{"2 • HTTPS BAĞLANTISINI BAŞLAT", "2 • START THE HTTPS CONNECTION"}
            ,{"TLS Parmak İzini Kopyala", "Copy TLS Fingerprint"}
            ,{"TLS kimliği ilk başlatmada oluşturulacak", "The TLS identity will be created on first start"}
            ,{"Aynı bilgisayar: LAN kutusunu işaretleme ve Tarayıcıda Aç'a bas.  •  Telefon/başka bilgisayar: LAN kutusunu aç, cihazı aynı Wi-Fi'a bağla ve HTTPS adresini yaz. İlk bağlantıda yerel sertifika uyarısı normaldir; SHA-256 parmak izini karşılaştırmadan ilerleme.", "Same computer: leave LAN unchecked and press Open in Browser.  •  Phone/another computer: enable LAN, join the same Wi-Fi, and enter the HTTPS address. A local-certificate warning is expected on first connection; do not proceed before comparing the SHA-256 fingerprint."}
        });
    }
    private LanguageManager() { }
    private static void putAll(String[][] pairs) { for (String[] pair : pairs) { TR_EN.put(pair[0], pair[1]); EN_TR.put(pair[1], pair[0]); } }
    public static String load() { Properties p = new Properties(); try { if (Files.exists(FILE)) try (Reader r = Files.newBufferedReader(FILE)) { p.load(r); } } catch (IOException ignored) { } return p.getProperty("language", "tr"); }
    public static void save(String language) { try { Files.createDirectories(FILE.getParent()); Properties p = new Properties(); p.setProperty("language", language); try (Writer w = Files.newBufferedWriter(FILE)) { p.store(w, "AeroMC UI"); } } catch (IOException ignored) { } }
    public static ReadOnlyBooleanProperty englishProperty() { return ENGLISH; }
    public static boolean isEnglish() { return ENGLISH.get(); }
    public static String text(String value) { return translate(value, ENGLISH.get()); }
    public static void apply(Parent root, String language) { ENGLISH.set("en".equals(language)); translateNode(root); save(language); }
    private static void translateNode(Node node) {
        if (node instanceof Labeled labeled) { if (!labeled.textProperty().isBound()) { localize(labeled.textProperty()); install(labeled); } if (labeled.getTooltip() != null) localize(labeled.getTooltip().textProperty()); }
        if (node instanceof TextInputControl input && !input.promptTextProperty().isBound()) { localize(input.promptTextProperty()); installPrompt(input); }
        if (node instanceof ComboBoxBase<?> combo && !combo.promptTextProperty().isBound()) localize(combo.promptTextProperty());
        if (node instanceof ComboBox<?> combo) translateCombo(combo);
        if (node instanceof TabPane tabs) for (Tab tab : tabs.getTabs()) { if (!tab.textProperty().isBound()) localize(tab.textProperty()); if (tab.getContent() != null) translateNode(tab.getContent()); }
        if (node instanceof TableView<?> table) { for (TableColumn<?, ?> column : table.getColumns()) translateColumn(column); if (table.getPlaceholder() != null) translateNode(table.getPlaceholder()); }
        if (node instanceof ListView<?> list && list.getPlaceholder() != null) translateNode(list.getPlaceholder());
        if (node instanceof ScrollPane scroll && scroll.getContent() != null) translateNode(scroll.getContent());
        if (node instanceof SplitPane split) split.getItems().forEach(LanguageManager::translateNode);
        if (node instanceof TitledPane titled && titled.getContent() != null) translateNode(titled.getContent());
        if (node instanceof Pane pane) pane.getChildrenUnmodifiable().forEach(LanguageManager::translateNode);
    }
    private static void translateColumn(TableColumnBase<?, ?> column) { if (!column.textProperty().isBound()) localize(column.textProperty()); if (column instanceof TableColumn<?, ?> c) for (TableColumn<?, ?> child : c.getColumns()) translateColumn(child); }
    @SuppressWarnings("unchecked")
    private static void translateCombo(ComboBox<?> combo) {
        boolean strings = combo.getItems().stream().filter(Objects::nonNull).findFirst().map(String.class::isInstance).orElse(combo.getValue() instanceof String);
        if (!strings) return;
        ComboBox<Object> values = (ComboBox<Object>) combo;
        values.setCellFactory(list -> localizedCell());
        values.setButtonCell(localizedCell());
    }
    private static ListCell<Object> localizedCell() {
        return new ListCell<>() {
            @Override protected void updateItem(Object item, boolean empty) {
                super.updateItem(item, empty);
                setText(empty || item == null ? null : text(String.valueOf(item)));
            }
        };
    }
    private static void install(Labeled labeled) { if (labeled.getProperties().containsKey(LABEL_LISTENER)) return; ChangeListener<String> listener = (obs, oldValue, newValue) -> localize(labeled.textProperty()); labeled.textProperty().addListener(listener); labeled.getProperties().put(LABEL_LISTENER, listener); }
    private static void installPrompt(TextInputControl input) { if (input.getProperties().containsKey(PROMPT_LISTENER)) return; ChangeListener<String> listener = (obs, oldValue, newValue) -> localize(input.promptTextProperty()); input.promptTextProperty().addListener(listener); input.getProperties().put(PROMPT_LISTENER, listener); }
    private static void localize(StringProperty property) { if (changing || property.isBound()) return; String before = property.get(), after = text(before); if (Objects.equals(before, after)) return; changing = true; try { property.set(after); } finally { changing = false; } }
    private static String translate(String value, boolean english) {
        if (value == null || value.isBlank()) return value; String exact = (english ? TR_EN : EN_TR).get(value); if (exact != null) return exact;
        if (english) {
            if (value.matches("\\d+ sunucu bulundu")) return value.replace(" sunucu bulundu", " servers found");
            if (value.startsWith("Hedef: ")) return "Target: " + value.substring("Hedef: ".length());
            if (value.startsWith("Filo durumu yenileniyor")) return "Refreshing fleet status...";
            if (value.startsWith("Filo durumu alınamadı")) return "Could not retrieve fleet status";
            if (value.startsWith("Seçili sunucu offline")) return value.replace("Seçili sunucu offline", "Selected server offline").replace("hesap geçmişindeki düşüş bu sunucunun anlık tüketimi değildir", "the decline in account history is not this server's instantaneous usage");
            if (value.startsWith("Sunucu kapalı")) return value.replace("Sunucu kapalı", "Server offline").replace("kredi korunuyor", "credits protected");
            if (value.startsWith("Kredi bağlantısı bekleniyor")) return "Waiting for credit connection";
            if (value.startsWith("Kredi yenileniyor")) return "Refreshing credits...";
            if (value.startsWith("Kredi bilgisi alınamadı")) return value.replace("Kredi bilgisi alınamadı", "Could not retrieve credit information").replace("bağlantıyı kontrol et", "check the connection");
            if (value.startsWith("Otomasyon beklemede")) return "Automation standing by";
            if (value.startsWith("Tüm otomasyonlar kapatıldı")) return "All automations disabled";
            if (value.matches("\\d+ oyuncu online")) return value.replace(" oyuncu online", " players online");
            if (value.startsWith("Kaydedildi: ")) return "Saved: " + value.substring(11);
            if (value.startsWith("Ölçek: ")) return value.replace("Ölçek:", "Scale:").replace("Nişan", "Target");
            if (value.endsWith(" GiB ayrılmış")) return value.replace(" GiB ayrılmış", " GiB allocated");
            if (value.endsWith("% kullanım")) return value.replace(" kullanım", " usage");
            if (value.startsWith("Kurulum tamamlandı: ")) return "Setup completed: " + value.substring("Kurulum tamamlandı: ".length());
            if (value.endsWith(" sunucuya katıldı.")) return value.replace(" sunucuya katıldı.", " joined the server.");
            if (value.startsWith("Açılacak adres: ")) return "Address to open: " + value.substring("Açılacak adres: ".length());
            if (value.startsWith("Açılacak güvenli adres: ")) return "Secure address to open: " + value.substring("Açılacak güvenli adres: ".length());
            if (value.startsWith("Algılandı: ")) return "Detected: " + value.substring("Algılandı: ".length()).replace("sürüm bulunamadı", "version not found").replace("loader bulunamadı", "loader not found").replace("Eksik alanı elle girebilirsin.", "You can fill in the missing field manually.");
            if (value.startsWith("Exaroton yazılımı algılanamadı: ")) return "Could not detect Exaroton software: " + value.substring("Exaroton yazılımı algılanamadı: ".length());
            if (value.endsWith(" uyumlu proje bulundu.")) return value.replace(" uyumlu proje bulundu.", " compatible projects found.");
            if (value.endsWith(" ve zorunlu bağımlılıkları hazırlanıyor...")) return value.replace(" ve zorunlu bağımlılıkları hazırlanıyor...", " and its required dependencies are being prepared...");
            if (value.startsWith("Aternos sayfasında “")) return value.replace("Aternos sayfasında “", "Search for “").replace("” adını arat. Otomatik yükleme Aternos tarafından desteklenmiyor.", "” on the Aternos page. Aternos does not support automatic installation.");
            if (value.contains(" dosya kuruldu (") || value.contains(" doğrulanmış dosya Exaroton ")) return value.replace(" dosya kuruldu (", " files installed (").replace(" doğrulanmış dosya Exaroton ", " verified files uploaded to Exaroton ").replace(" klasörüne yüklendi (", " folder (").replace(" bağımlılık). Güvenlik yedeği: ", " dependencies). Safety backup: ").replace(" bağımlılık).", " dependencies).").replace(" Sunucuyu yeniden başlatınca etkinleşecek.", " Restart the server to activate them.");
            if (value.contains("\nGeliştirici: ")) return value.replace("\nGeliştirici: ", "\nDeveloper: ").replace("Sunucu desteği: ", "Server support: ").replace(" indirme", " downloads");
            if (value.contains(" indirme\n")) return value.replace(" indirme\n", " downloads\n");
            if (value.startsWith("Tarayıcı açılamadı. Adresi elle açabilirsin:\n")) return "The browser could not be opened. Open this address manually:\n" + value.substring("Tarayıcı açılamadı. Adresi elle açabilirsin:\n".length());
            if (value.startsWith("GÜNCELLEME  •  ") || value.startsWith("GÜNCEL  •  ") || value.startsWith("TANINMADI  •  ") || value.startsWith("UYUMSUZ  •  ")) return value.replaceFirst("^GÜNCELLEME", "UPDATE").replaceFirst("^GÜNCEL", "CURRENT").replaceFirst("^TANINMADI", "UNRECOGNIZED").replaceFirst("^UYUMSUZ", "INCOMPATIBLE");
            if (value.contains(" JAR incelendi • ")) return value.replace(" JAR incelendi", " JARs scanned").replace(" güncelleme", " updates").replace(" kritik", " critical").replace(" uyarı", " warnings");
            if (value.endsWith(" proje ve gereken bağımlılıklar yedek alınarak güncellensin mi?")) return value.replace(" proje ve gereken bağımlılıklar yedek alınarak güncellensin mi?", " projects and required dependencies be updated after creating a backup?");
            if (value.contains(" dosya güncellendi. Güvenlik yedeği: ")) return value.replace(" dosya güncellendi. Güvenlik yedeği: ", " files updated. Safety backup: ").replace(" Sunucuyu yeniden başlatınca etkinleşecek.", " Restart the server to activate them.");
            if (value.contains(" dosya Exaroton'da güncellendi. Yerel güvenlik yedeği: ")) return value.replace(" dosya Exaroton'da güncellendi. Yerel güvenlik yedeği: ", " files updated on Exaroton. Local safety backup: ").replace(" Sunucuyu yeniden başlatınca etkinleşecek.", " Restart the server to activate them.");
            if (value.contains("Modrinth'te tanınmadı; otomatik güncellenmeyecek.")) return value.replace("Modrinth'te tanınmadı; otomatik güncellenmeyecek.", "Not recognized by Modrinth; it will not be updated automatically.");
            if (value.contains(" için uyumlu sürüm bulunamadı.")) return value.replace(" için uyumlu sürüm bulunamadı.", " has no compatible version.");
            if (value.contains("Kurulu sürüm hedef Minecraft/loader ile uyumlu görünmüyor.")) return value.replace("Kurulu sürüm hedef Minecraft/loader ile uyumlu görünmüyor.", "The installed version does not appear compatible with the target Minecraft version/loader.");
            if (value.contains("Zorunlu bağımlılık eksik: ")) return value.replace("Zorunlu bağımlılık eksik: ", "Missing required dependency: ").replace(" • güncellemede otomatik eklenecek.", " • it will be added automatically during the update.");
            if (value.contains("Bağımlılık sürümü hizalanmalı: ")) return value.replace("Bağımlılık sürümü hizalanmalı: ", "Dependency version must be aligned: ").replace(" • kurulum öncesi kesin çözüm yapılacak.", " • exact resolution will run before installation.");
            if (value.contains("Uyumsuz proje birlikte kurulu: ")) return value.replace("Uyumsuz proje birlikte kurulu: ", "An incompatible project is installed: ");
        } else {
            if (value.matches("\\d+ servers found")) return value.replace(" servers found", " sunucu bulundu");
            if (value.startsWith("Target: ")) return "Hedef: " + value.substring("Target: ".length());
            if (value.startsWith("Refreshing fleet status")) return "Filo durumu yenileniyor...";
            if (value.startsWith("Could not retrieve fleet status")) return "Filo durumu alınamadı";
            if (value.startsWith("Selected server offline")) return value.replace("Selected server offline", "Seçili sunucu offline").replace("the decline in account history is not this server's instantaneous usage", "hesap geçmişindeki düşüş bu sunucunun anlık tüketimi değildir");
            if (value.startsWith("Server offline")) return value.replace("Server offline", "Sunucu kapalı").replace("credits protected", "kredi korunuyor");
            if (value.startsWith("Waiting for credit connection")) return "Kredi bağlantısı bekleniyor";
            if (value.startsWith("Refreshing credits")) return "Kredi yenileniyor...";
            if (value.startsWith("Could not retrieve credit information")) return value.replace("Could not retrieve credit information", "Kredi bilgisi alınamadı").replace("check the connection", "bağlantıyı kontrol et");
            if (value.startsWith("Automation standing by")) return "Otomasyon beklemede";
            if (value.startsWith("All automations disabled")) return "Tüm otomasyonlar kapatıldı";
            if (value.matches("\\d+ players online")) return value.replace(" players online", " oyuncu online");
            if (value.startsWith("Saved: ")) return "Kaydedildi: " + value.substring(7);
            if (value.startsWith("Scale: ")) return value.replace("Scale:", "Ölçek:").replace("Target", "Nişan");
            if (value.endsWith(" GiB allocated")) return value.replace(" GiB allocated", " GiB ayrılmış");
            if (value.endsWith("% usage")) return value.replace(" usage", " kullanım");
            if (value.startsWith("Setup completed: ")) return "Kurulum tamamlandı: " + value.substring("Setup completed: ".length());
            if (value.endsWith(" joined the server.")) return value.replace(" joined the server.", " sunucuya katıldı.");
            if (value.startsWith("Address to open: ")) return "Açılacak adres: " + value.substring("Address to open: ".length());
            if (value.startsWith("Detected: ")) return "Algılandı: " + value.substring("Detected: ".length()).replace("version not found", "sürüm bulunamadı").replace("loader not found", "loader bulunamadı").replace("You can fill in the missing field manually.", "Eksik alanı elle girebilirsin.");
            if (value.startsWith("Could not detect Exaroton software: ")) return "Exaroton yazılımı algılanamadı: " + value.substring("Could not detect Exaroton software: ".length());
            if (value.endsWith(" compatible projects found.")) return value.replace(" compatible projects found.", " uyumlu proje bulundu.");
            if (value.endsWith(" and its required dependencies are being prepared...")) return value.replace(" and its required dependencies are being prepared...", " ve zorunlu bağımlılıkları hazırlanıyor...");
            if (value.startsWith("Search for “") && value.endsWith("” on the Aternos page. Aternos does not support automatic installation.")) return value.replace("Search for “", "Aternos sayfasında “").replace("” on the Aternos page. Aternos does not support automatic installation.", "” adını arat. Otomatik yükleme Aternos tarafından desteklenmiyor.");
            if (value.contains(" files installed (") || value.contains(" verified files uploaded to Exaroton ")) return value.replace(" files installed (", " dosya kuruldu (").replace(" verified files uploaded to Exaroton ", " doğrulanmış dosya Exaroton ").replace(" folder (", " klasörüne yüklendi (").replace(" dependencies). Safety backup: ", " bağımlılık). Güvenlik yedeği: ").replace(" dependencies).", " bağımlılık).").replace(" Restart the server to activate them.", " Sunucuyu yeniden başlatınca etkinleşecek.");
            if (value.contains("\nDeveloper: ")) return value.replace("\nDeveloper: ", "\nGeliştirici: ").replace("Server support: ", "Sunucu desteği: ").replace(" downloads", " indirme");
            if (value.contains(" downloads\n")) return value.replace(" downloads\n", " indirme\n");
            if (value.startsWith("The browser could not be opened. Open this address manually:\n")) return "Tarayıcı açılamadı. Adresi elle açabilirsin:\n" + value.substring("The browser could not be opened. Open this address manually:\n".length());
            if (value.startsWith("UPDATE  •  ") || value.startsWith("CURRENT  •  ") || value.startsWith("UNRECOGNIZED  •  ") || value.startsWith("INCOMPATIBLE  •  ")) return value.replaceFirst("^UPDATE", "GÜNCELLEME").replaceFirst("^CURRENT", "GÜNCEL").replaceFirst("^UNRECOGNIZED", "TANINMADI").replaceFirst("^INCOMPATIBLE", "UYUMSUZ");
            if (value.contains(" JARs scanned • ")) return value.replace(" JARs scanned", " JAR incelendi").replace(" updates", " güncelleme").replace(" critical", " kritik").replace(" warnings", " uyarı");
            if (value.endsWith(" projects and required dependencies be updated after creating a backup?")) return value.replace(" projects and required dependencies be updated after creating a backup?", " proje ve gereken bağımlılıklar yedek alınarak güncellensin mi?");
            if (value.contains(" files updated. Safety backup: ")) return value.replace(" files updated. Safety backup: ", " dosya güncellendi. Güvenlik yedeği: ").replace(" Restart the server to activate them.", " Sunucuyu yeniden başlatınca etkinleşecek.");
            if (value.contains(" files updated on Exaroton. Local safety backup: ")) return value.replace(" files updated on Exaroton. Local safety backup: ", " dosya Exaroton'da güncellendi. Yerel güvenlik yedeği: ").replace(" Restart the server to activate them.", " Sunucuyu yeniden başlatınca etkinleşecek.");
            if (value.contains("Not recognized by Modrinth; it will not be updated automatically.")) return value.replace("Not recognized by Modrinth; it will not be updated automatically.", "Modrinth'te tanınmadı; otomatik güncellenmeyecek.");
            if (value.contains(" has no compatible version.")) return value.replace(" has no compatible version.", " için uyumlu sürüm bulunamadı.");
            if (value.contains("The installed version does not appear compatible with the target Minecraft version/loader.")) return value.replace("The installed version does not appear compatible with the target Minecraft version/loader.", "Kurulu sürüm hedef Minecraft/loader ile uyumlu görünmüyor.");
            if (value.contains("Missing required dependency: ")) return value.replace("Missing required dependency: ", "Zorunlu bağımlılık eksik: ").replace(" • it will be added automatically during the update.", " • güncellemede otomatik eklenecek.");
            if (value.contains("Dependency version must be aligned: ")) return value.replace("Dependency version must be aligned: ", "Bağımlılık sürümü hizalanmalı: ").replace(" • exact resolution will run before installation.", " • kurulum öncesi kesin çözüm yapılacak.");
            if (value.contains("An incompatible project is installed: ")) return value.replace("An incompatible project is installed: ", "Uyumsuz proje birlikte kurulu: ");
        }
        return value;
    }
}
