package com.aerogroup.mcpanel;

import com.google.gson.*;
import javafx.application.HostServices;
import javafx.application.Platform;
import javafx.beans.property.ReadOnlyStringWrapper;
import javafx.collections.*;
import javafx.concurrent.Task;
import javafx.geometry.*;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.*;

import java.io.*;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.nio.file.attribute.PosixFilePermission;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.function.BiConsumer;
import java.util.regex.*;
import java.util.zip.*;

/** Kurulum, uyumluluk, yedek, optimizasyon ve uzaktan erişim araçları. */
public final class NextGenPane {
    private static final int MAX_METADATA_BYTES = 4 * 1024 * 1024;
    private static final long MAX_SERVER_JAR_BYTES = 750L * 1024 * 1024;
    private static final String USER_AGENT = "AeroMC-Server-Panel/2.0 (desktop app; https://openai.com)";
    private final ServerManager manager;
    private final ExarotonPane exaroton;
    private final PanelConfig config;
    private final HostServices hostServices;
    private final BiConsumer<Path, Integer> installedJar;
    private final Runnable openGameOverlay;
    private final java.util.function.Supplier<Node> profilesView;
    private final RemoteControlService remote;
    private final SparkInstaller sparkInstaller = new SparkInstaller();
    private final HttpClient http = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NORMAL).connectTimeout(java.time.Duration.ofSeconds(15)).build();
    private final TextField installFolder = new TextField(), gameVersion = new TextField("1.20.4");
    private final ComboBox<String> platform = new ComboBox<>(FXCollections.observableArrayList("Paper", "Fabric", "Vanilla"));
    private final ComboBox<String> template = new ComboBox<>(FXCollections.observableArrayList("Survival", "SMP", "Creative", "SkyBlock Temeli", "Modlu Sunucu"));
    private final Spinner<Integer> installRam = new Spinner<>(1024, 32768, 4096, 512);
    private final CheckBox acceptEula = new CheckBox("Minecraft EULA koşullarını okudum ve kabul ediyorum");
    private final CheckBox installSpark = new CheckBox("Spark'ı da ekle (önerilir)");
    private final Label sparkInstallNote = new Label();
    private final ProgressBar installProgress = new ProgressBar(0);
    private final Label installState = new Label("Hazır");
    private final ObservableList<CompatResult> compatibility = FXCollections.observableArrayList();
    private final ObservableList<Path> backups = FXCollections.observableArrayList();
    private final ObservableList<LocalServerTarget> serverTargets = FXCollections.observableArrayList();
    private final ComboBox<LocalServerTarget> compatibilityTarget = new ComboBox<>(), backupTarget = new ComboBox<>();
    private final Label compatibilityState = new Label("Sunucu seçimi bekleniyor"), backupState = new Label("Sunucu seçimi bekleniyor");
    private final ObservableList<String> suggestions = FXCollections.observableArrayList();
    private final ObservableList<String> users = FXCollections.observableArrayList();
    private final ObservableList<RemoteControlService.AuditEntry> audit = FXCollections.observableArrayList();
    private final Label remoteState = new Label("Kapalı"), remoteTlsState = new Label("TLS kimliği ilk başlatmada oluşturulacak");

    public NextGenPane(ServerManager manager, ExarotonPane exaroton, PanelConfig config, HostServices hostServices, BiConsumer<Path, Integer> installedJar, Runnable openGameOverlay, java.util.function.Supplier<Node> profilesView) {
        this.manager = manager; this.exaroton = exaroton; this.config = config; this.hostServices = hostServices; this.installedJar = installedJar; this.openGameOverlay = openGameOverlay; this.profilesView = profilesView; this.remote = new RemoteControlService(manager, exaroton, config);
    }
    public Node buildView() {
        Tab setup = tab("Kurulum", setupView()), compat = tab("Uyumluluk", compatibilityView()), backup = tab("Yedekler", backupView()), optimization = tab("Optimizasyon", optimizationView()), profiles = tab("Sunucu Profilleri", profilesView.get()), overlay = tab("Oyun Yardımcısı", overlayView()), access = tab("Uzaktan Erişim", remoteView());
        TabPane tabs = new TabPane(setup, compat, backup, optimization, profiles, overlay, access);
        tabs.getStyleClass().add("inner-tabs"); tabs.getSelectionModel().selectedItemProperty().addListener((obs, oldTab, newTab) -> { if (newTab == compat) refreshServerTargets(); if (newTab == backup) { refreshServerTargets(); refreshBackups(); } if (newTab == access) refreshSecurity(); }); return tabs;
    }

    private Node overlayView() {
        Label detail = new Label("Minecraft'a mod kurmadan, AeroMC'nin yetkili olduğu Yerel JAR, Exaroton ve Pterodactyl sunucuları için oyunun üzerinde küçük bir yardımcı pencere açar. Sağlık özeti, oyuncu sayısı ve kaynak bilgisi gösterir; duyurular AeroMC üzerinden güvenle gönderilir."); detail.setWrapText(true); detail.getStyleClass().add("muted");
        Label safety = new Label("API anahtarları overlay'e aktarılmaz; anahtarlar yalnız AeroMC'nin güvenli kasasında kalır. Pencere her zaman üstte çalışır ve Gizle ile kapatılabilir."); safety.setWrapText(true); safety.getStyleClass().add("muted");
        Button open = button("OYUN YARDIMCISINI AÇ", "primary"); open.setOnAction(event -> openGameOverlay.run());
        return page(card("AEROMC OYUN YARDIMCISI", detail, safety, open));
    }

    private Node setupView() {
        platform.getSelectionModel().selectFirst(); template.getSelectionModel().selectFirst(); installFolder.setEditable(false); installFolder.setPromptText("Yeni sunucu klasörünü seç"); HBox.setHgrow(installFolder, Priority.ALWAYS);
        Button choose = button("Klasör Seç", "secondary"); choose.setOnAction(event -> chooseInstallFolder()); HBox folder = new HBox(8, installFolder, choose);
        GridPane options = new GridPane(); options.setHgap(12); options.setVgap(10); addField(options, 0, "Platform", platform); addField(options, 1, "Minecraft sürümü", gameVersion); addField(options, 2, "Şablon", template); addField(options, 3, "RAM (MB)", installRam);
        installProgress.setMaxWidth(Double.MAX_VALUE); installState.getStyleClass().add("muted"); sparkInstallNote.setWrapText(true); sparkInstallNote.getStyleClass().add("muted"); platform.valueProperty().addListener((obs, old, value) -> updateSparkInstallOption()); gameVersion.textProperty().addListener((obs, old, value) -> updateSparkInstallOption()); updateSparkInstallOption(); Button install = button("SUNUCUYU HAZIRLA", "primary"); install.setOnAction(event -> installServer());
        Hyperlink eulaLink = new Hyperlink("Güncel Minecraft EULA'sını Aç ↗"); eulaLink.setOnAction(event -> openLegalPage(MinecraftEula.EULA_URL));
        Hyperlink usageLink = new Hyperlink("Minecraft Kullanım Kurallarını Aç ↗"); usageLink.setOnAction(event -> openLegalPage(MinecraftEula.USAGE_GUIDELINES_URL));
        HBox legalLinks = new HBox(14, eulaLink, usageLink); legalLinks.setAlignment(Pos.CENTER_LEFT);
        Label legal = new Label("EULA metni AeroMC içine kopyalanmaz; yukarıdaki resmî ve güncel Minecraft sayfasından okunur. Onay kutusu yalnızca sen işaretlediğinde eula.txt oluşturulur. İndirmeler resmî PaperMC, Fabric veya Mojang kaynaklarından yapılır."); legal.setWrapText(true); legal.getStyleClass().add("muted");
        VBox wizard = card("TEK TIK SUNUCU KURULUM SİHİRBAZI", folder, options, installSpark, sparkInstallNote, legalLinks, acceptEula, legal, installProgress, installState, install);
        Label templates = new Label("Survival: dengeli varsayılanlar  •  SMP: whitelist ve topluluk ayarları  •  Creative: yaratıcı mod  •  SkyBlock Temeli: boş/flat dünya tabanı  •  Modlu: Fabric uyumlu temel"); templates.setWrapText(true); templates.getStyleClass().add("muted");
        return page(wizard, card("HAZIR SUNUCU ŞABLONLARI", templates));
    }
    private void updateSparkInstallOption() {
        String selectedPlatform = platform.getValue(), version = gameVersion.getText(); boolean supported = SparkInstaller.supports(selectedPlatform, version);
        installSpark.setVisible(supported); installSpark.setManaged(supported); installSpark.setDisable(!supported); if (!supported) installSpark.setSelected(false);
        if ("Paper".equals(selectedPlatform) && !SparkInstaller.isBefore121(version)) sparkInstallNote.setText("Paper 1.21 ve üzeri Spark profiler'ı zaten içinde getirir; ayrıca indirmeye gerek yok.");
        else if ("Vanilla".equals(selectedPlatform)) sparkInstallNote.setText("Vanilla sunucu eklenti/mod yükleyemediği için Spark otomatik eklenemez.");
        else if (supported) sparkInstallNote.setText("Seçersen AeroMC uyumlu Spark JAR'ını doğrulayıp " + ("Paper".equals(selectedPlatform) ? "plugins" : "mods") + " klasörüne koyar.");
        else sparkInstallNote.setText("Spark hızlı ekleme, 1.21 öncesi Paper ve Fabric kurulumlarında gösterilir.");
    }
    private void chooseInstallFolder() { DirectoryChooser chooser = new DirectoryChooser(); chooser.setTitle("Yeni sunucu klasörünü seç"); File selected = chooser.showDialog(installFolder.getScene().getWindow()); if (selected != null) installFolder.setText(selected.getAbsolutePath()); }
    private void installServer() {
        if (installFolder.getText().isBlank()) { error("Kurulum klasörünü seç."); return; } if (!acceptEula.isSelected()) { error("Kurulum için Minecraft EULA koşullarını okuyup kabul etmelisin."); return; }
        Path folder = Path.of(installFolder.getText()), jar = folder.resolve("server.jar"); String selectedPlatform = platform.getValue(), version = gameVersion.getText().trim(), selectedTemplate = template.getValue(); int ram = installRam.getValue(); boolean addSpark = installSpark.isSelected() && SparkInstaller.supports(selectedPlatform, version);
        int requiredJava = requiredJava(version); int currentJava = Runtime.version().feature(); if (currentJava < requiredJava && !confirm("Bu sürüm yaklaşık Java " + requiredJava + " gerektiriyor; panel şu anda Java " + currentJava + " ile çalışıyor. Yine de indirilsin mi?")) return;
        installProgress.setProgress(-1); installState.setText("Resmî indirme adresi hazırlanıyor...");
        Task<SetupResult> task = new Task<>() { protected SetupResult call() throws Exception { Files.createDirectories(folder); URI uri = downloadUri(selectedPlatform, version); download(uri, jar); writeTemplate(folder, selectedTemplate); writeServerMetadata(folder, selectedPlatform, version); MinecraftEula.writeAccepted(folder); writeLaunchers(folder, ram); SparkInstaller.InstallResult spark = addSpark ? sparkInstaller.install(folder, selectedPlatform, version) : null; return new SetupResult(jar, spark); } };
        task.setOnSucceeded(event -> { installProgress.setProgress(1); SparkInstaller.InstallResult spark = task.getValue().spark(); String sparkText = spark == null ? "" : " Spark da " + spark.verification() + " doğrulamasıyla eklendi."; installState.setText("Kurulum tamamlandı: " + jar + (spark == null ? "" : " • Spark hazır")); installedJar.accept(jar, ram); info("Sunucu hazır", "server.jar ve " + ram + " MB RAM ayarı seçildi." + sparkText + " Yerel JAR sekmesinden başlatabilirsin."); }); task.setOnFailed(event -> { installProgress.setProgress(0); installState.setText("Kurulum başarısız"); error(rootMessage(task.getException())); }); run(task, "server-installer");
    }
    private void openLegalPage(String url) {
        try { hostServices.showDocument(url); }
        catch (RuntimeException error) { info("Bağlantı açılamadı", "Resmî adresi tarayıcıda açabilirsin:\n" + url); }
    }
    private URI downloadUri(String selectedPlatform, String version) throws Exception {
        return switch (selectedPlatform) { case "Paper" -> paperUri(version); case "Fabric" -> fabricUri(version); default -> vanillaUri(version); };
    }
    private URI paperUri(String version) throws Exception {
        JsonArray builds = jsonGet("https://fill.papermc.io/v3/projects/paper/versions/" + encode(version) + "/builds").getAsJsonArray();
        for (JsonElement element : builds) { JsonObject build = element.getAsJsonObject(); if (!"STABLE".equalsIgnoreCase(build.get("channel").getAsString())) continue; JsonObject downloads = build.getAsJsonObject("downloads"); JsonObject server = downloads.getAsJsonObject("server:default"); if (server != null) return URI.create(server.get("url").getAsString()); }
        throw new IOException("Bu Paper sürümü için kararlı yapı bulunamadı.");
    }
    private URI fabricUri(String version) throws Exception {
        JsonArray loaders = jsonGet("https://meta.fabricmc.net/v2/versions/loader/" + encode(version)).getAsJsonArray(); if (loaders.isEmpty()) throw new IOException("Bu Minecraft sürümü için Fabric Loader bulunamadı.");
        JsonObject first = loaders.get(0).getAsJsonObject(); String loader = first.getAsJsonObject("loader").get("version").getAsString(); JsonArray installers = jsonGet("https://meta.fabricmc.net/v2/versions/installer").getAsJsonArray(); String installer = installers.get(0).getAsJsonObject().get("version").getAsString();
        return URI.create("https://meta.fabricmc.net/v2/versions/loader/" + encode(version) + "/" + encode(loader) + "/" + encode(installer) + "/server/jar");
    }
    private URI vanillaUri(String version) throws Exception {
        JsonObject manifest = jsonGet("https://piston-meta.mojang.com/mc/game/version_manifest_v2.json").getAsJsonObject(); String metadata = null; for (JsonElement item : manifest.getAsJsonArray("versions")) if (version.equals(item.getAsJsonObject().get("id").getAsString())) { metadata = item.getAsJsonObject().get("url").getAsString(); break; } if (metadata == null) throw new IOException("Mojang manifestinde bu sürüm bulunamadı.");
        JsonObject details = jsonGet(metadata).getAsJsonObject(); return URI.create(details.getAsJsonObject("downloads").getAsJsonObject("server").get("url").getAsString());
    }
    private JsonElement jsonGet(String url) throws Exception { URI uri = URI.create(url); requireOfficialDownload(uri); HttpRequest request = HttpRequest.newBuilder(uri).header("User-Agent", USER_AGENT).timeout(java.time.Duration.ofSeconds(20)).GET().build(); HttpResponse<InputStream> response = http.send(request, HttpResponse.BodyHandlers.ofInputStream()); if (response.statusCode() / 100 != 2) { response.body().close(); throw new IOException("İndirme servisi HTTP " + response.statusCode() + " döndürdü."); } requireOfficialDownload(response.uri()); return JsonParser.parseString(BoundedStreams.readString(response.body(), MAX_METADATA_BYTES, StandardCharsets.UTF_8)); }
    private void download(URI uri, Path output) throws Exception { requireOfficialDownload(uri); Path temp = Files.createTempFile(output.getParent(), "server-", ".download"); try { HttpRequest request = HttpRequest.newBuilder(uri).header("User-Agent", USER_AGENT).timeout(java.time.Duration.ofMinutes(5)).GET().build(); HttpResponse<InputStream> response = http.send(request, HttpResponse.BodyHandlers.ofInputStream()); if (response.statusCode() / 100 != 2) { response.body().close(); throw new IOException("Sunucu JAR indirilemedi (HTTP " + response.statusCode() + ")."); } requireOfficialDownload(response.uri()); long downloaded = BoundedStreams.copyToFile(response.body(), temp, MAX_SERVER_JAR_BYTES); if (downloaded < 100_000) throw new IOException("Sunucu JAR indirilemedi veya geçersiz."); Files.move(temp, output, StandardCopyOption.REPLACE_EXISTING); } finally { Files.deleteIfExists(temp); } }
    private static void requireOfficialDownload(URI uri) throws IOException { String host = uri == null ? "" : Objects.toString(uri.getHost(), "").toLowerCase(Locale.ROOT); boolean official = host.equals("fill.papermc.io") || host.equals("fill-data.papermc.io") || host.equals("meta.fabricmc.net") || host.equals("piston-meta.mojang.com") || host.equals("piston-data.mojang.com") || host.equals("launcher.mojang.com"); if (uri == null || !"https".equalsIgnoreCase(uri.getScheme()) || !official || uri.getUserInfo() != null) throw new IOException("Sunucu dosyası yalnızca resmî HTTPS kaynağından indirilebilir."); }
    private void writeTemplate(Path folder, String selected) throws IOException { Properties p = new Properties(); p.setProperty("motd", "AeroMC " + selected + " Server"); p.setProperty("max-players", selected.equals("SMP") ? "30" : "20"); p.setProperty("difficulty", selected.equals("Creative") ? "peaceful" : "normal"); p.setProperty("gamemode", selected.equals("Creative") ? "creative" : "survival"); p.setProperty("pvp", Boolean.toString(!selected.equals("Creative"))); p.setProperty("white-list", Boolean.toString(selected.equals("SMP"))); p.setProperty("view-distance", selected.equals("Modlu Sunucu") ? "7" : "10"); p.setProperty("simulation-distance", selected.equals("Modlu Sunucu") ? "5" : "8"); if (selected.equals("SkyBlock Temeli")) { p.setProperty("level-type", "minecraft:flat"); p.setProperty("generate-structures", "false"); } try (Writer writer = Files.newBufferedWriter(folder.resolve("server.properties"))) { p.store(writer, "AeroMC " + selected + " template"); } }
    private void writeServerMetadata(Path folder, String selectedPlatform, String version) throws IOException { Properties metadata = new Properties(); metadata.setProperty("minecraftVersion", version); metadata.setProperty("loader", selectedPlatform.toLowerCase(Locale.ROOT)); try (Writer writer = Files.newBufferedWriter(folder.resolve(".aeromc-server.properties"), StandardCharsets.UTF_8)) { metadata.store(writer, "AeroMC detected server metadata"); } }
    private void writeLaunchers(Path folder, int ram) throws IOException { Files.writeString(folder.resolve("start.bat"), "@echo off\r\njava -Xms" + Math.max(512, ram / 2) + "M -Xmx" + ram + "M -jar server.jar nogui\r\npause\r\n"); Path sh = folder.resolve("start.sh"); Files.writeString(sh, "#!/usr/bin/env sh\njava -Xms" + Math.max(512, ram / 2) + "M -Xmx" + ram + "M -jar server.jar nogui\n"); try { Files.setPosixFilePermissions(sh, Set.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE, PosixFilePermission.OWNER_EXECUTE, PosixFilePermission.GROUP_READ, PosixFilePermission.GROUP_EXECUTE)); } catch (UnsupportedOperationException ignored) { } }

    private Node compatibilityView() {
        TableView<CompatResult> table = new TableView<>(compatibility); table.getColumns().add(col("Dosya", r -> r.file)); table.getColumns().add(col("Tür", r -> r.type)); table.getColumns().add(col("Durum", r -> r.level)); table.getColumns().add(col("Açıklama", r -> r.message)); table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN); VBox.setVgrow(table, Priority.ALWAYS);
        compatibilityTarget.setItems(serverTargets); compatibilityTarget.setMaxWidth(Double.MAX_VALUE); compatibilityTarget.setPromptText("Taranacak sunucuyu seç"); compatibilityTarget.setOnAction(event -> updateCompatibilityState()); HBox.setHgrow(compatibilityTarget, Priority.ALWAYS);
        Button choose = button("JAR Seç", "secondary"), refresh = button("Senkronize Et", "secondary"), scan = button("UYUMLULUĞU TARA", "primary"); choose.setOnAction(event -> chooseExistingServer()); refresh.setOnAction(event -> refreshServerTargets()); scan.setOnAction(event -> scanCompatibility());
        compatibilityState.getStyleClass().add("muted"); HBox target = new HBox(8, compatibilityTarget, choose, refresh, scan); target.setAlignment(Pos.CENTER_LEFT);
        Label note = new Label("Seçili sunucunun plugins ve mods klasörleri birlikte taranır. Sunucu değiştirildiğinde liste otomatik senkronize edilir."); note.setWrapText(true); note.getStyleClass().add("muted"); refreshServerTargets(); return page(card("EKLENTİ / MOD UYUMLULUK KONTROLÜ", note, target, compatibilityState, table));
    }
    private void scanCompatibility() { LocalServerTarget selected = compatibilityTarget.getValue(); if (selected == null) { error("Önce taranacak yerel sunucuyu seç."); return; } Path root = selected.folder(); compatibility.clear(); compatibilityState.setText("Taranıyor: " + root); Task<List<CompatResult>> task = new Task<>() { protected List<CompatResult> call() throws Exception { return inspectJars(root); } }; task.setOnSucceeded(event -> { compatibility.setAll(task.getValue()); long issues = task.getValue().stream().filter(value -> !"UYGUN".equals(value.level) && !"BİLGİ".equals(value.level)).count(); compatibilityState.setText(task.getValue().size() + " sonuç • " + issues + " sorun • " + selected.name()); }); task.setOnFailed(event -> { compatibilityState.setText("Tarama başarısız"); error(rootMessage(task.getException())); }); run(task, "compatibility-scan"); }
    static List<CompatResult> inspectJars(Path root) throws IOException { List<JarInfo> jars = new ArrayList<>(); for (String directory : List.of("plugins", "mods")) { Path folder = root.resolve(directory); if (!Files.isDirectory(folder)) continue; try (var files = Files.list(folder)) { for (Path file : files.filter(path -> path.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".jar")).toList()) jars.add(inspectJar(file, directory)); } } if (jars.isEmpty()) return List.of(new CompatResult("-", "Bilgi", "BİLGİ", "Seçili sunucunun plugins veya mods klasöründe JAR bulunamadı.")); Set<String> ids = new HashSet<>(); for (JarInfo jar : jars) ids.add(jar.id.toLowerCase(Locale.ROOT)); List<CompatResult> result = new ArrayList<>(); Set<String> seen = new HashSet<>(); for (JarInfo jar : jars) { if (jar.error != null) { result.add(new CompatResult(jar.file, jar.type, "HATA", jar.error)); continue; } String key = jar.id.toLowerCase(Locale.ROOT); if (!seen.add(key)) result.add(new CompatResult(jar.file, jar.type, "UYARI", "Yinelenen eklenti/mod kimliği: " + jar.id)); else if (!ids.containsAll(jar.required.stream().map(v -> v.toLowerCase(Locale.ROOT)).toList())) { List<String> missing = jar.required.stream().filter(dep -> !ids.contains(dep.toLowerCase(Locale.ROOT))).toList(); result.add(new CompatResult(jar.file, jar.type, "UYARI", "Eksik bağımlılıklar: " + String.join(", ", missing))); } else result.add(new CompatResult(jar.file, jar.type, "UYGUN", jar.id + " • " + jar.version)); } return result; }
    private static JarInfo inspectJar(Path file, String type) { try (ZipFile zip = new ZipFile(file.toFile())) { ZipEntry plugin = firstEntry(zip, "plugin.yml", "paper-plugin.yml", "bungee.yml"), fabric = zip.getEntry("fabric.mod.json"), forge = firstEntry(zip, "META-INF/mods.toml", "META-INF/neoforge.mods.toml"); if (plugin != null) { String text = readEntry(zip, plugin); String id = yaml(text, "name", stem(file)), version = yaml(text, "version", "?"); List<String> deps = yamlList(text, "depend"); return new JarInfo(file.getFileName().toString(), plugin.getName().equals("paper-plugin.yml") ? "Paper Plugin" : "Plugin", id, version, deps, null); } if (fabric != null) { JsonObject json = JsonParser.parseString(readEntry(zip, fabric)).getAsJsonObject(); String id = string(json, "id", stem(file)), version = string(json, "version", "?"); List<String> deps = new ArrayList<>(); if (json.has("depends") && json.get("depends").isJsonObject()) for (String key : json.getAsJsonObject("depends").keySet()) if (!Set.of("minecraft", "java", "fabricloader").contains(key)) deps.add(key); return new JarInfo(file.getFileName().toString(), "Fabric Mod", id, version, deps, null); } if (forge != null) { String text = readEntry(zip, forge); String id = toml(text, "modId", stem(file)), version = toml(text, "version", "?"); return new JarInfo(file.getFileName().toString(), forge.getName().contains("neoforge") ? "NeoForge Mod" : "Forge Mod", id, version, List.of(), null); } return new JarInfo(file.getFileName().toString(), type, stem(file), "?", List.of(), "Desteklenen tanım dosyası bulunamadı (plugin.yml, paper-plugin.yml, fabric.mod.json veya mods.toml)."); } catch (Exception error) { return new JarInfo(file.getFileName().toString(), type, stem(file), "?", List.of(), "Bozuk veya okunamayan JAR: " + error.getMessage()); } }
    private static ZipEntry firstEntry(ZipFile zip, String... names) { for (String name : names) { ZipEntry entry = zip.getEntry(name); if (entry != null) return entry; } return null; }
    private static String readEntry(ZipFile zip, ZipEntry entry) throws IOException { try (InputStream input = zip.getInputStream(entry)) { return new String(input.readNBytes(2_000_000), StandardCharsets.UTF_8); } }
    private static String yaml(String text, String key, String fallback) { Matcher m = Pattern.compile("(?m)^" + Pattern.quote(key) + ":[ \\t]*[\"']?([^\\r\\n\"']+)").matcher(text); return m.find() ? m.group(1).trim() : fallback; }
    private static List<String> yamlList(String text, String key) { String raw = yaml(text, key, "").replace("[", "").replace("]", ""); if (!raw.isBlank()) return Arrays.stream(raw.split(",")).map(String::trim).map(value -> value.replaceAll("^[\"']|[\"']$", "")).filter(v -> !v.isBlank()).toList(); Matcher block = Pattern.compile("(?ms)^" + Pattern.quote(key) + ":\\s*\\R((?:\\s+-\\s*[^\\r\\n]+\\R?)+)").matcher(text); if (!block.find()) return List.of(); Matcher item = Pattern.compile("(?m)^\\s+-\\s*[\"']?([^\\r\\n\"']+)").matcher(block.group(1)); List<String> values = new ArrayList<>(); while (item.find()) values.add(item.group(1).trim()); return values; }
    private static String toml(String text, String key, String fallback) { Matcher matcher = Pattern.compile("(?m)^\\s*" + Pattern.quote(key) + "\\s*=\\s*[\"']([^\"']+)").matcher(text); return matcher.find() ? matcher.group(1).trim() : fallback; }

    private void refreshServerTargets() {
        Path selectedCompat = compatibilityTarget.getValue() == null ? null : compatibilityTarget.getValue().jar(); Path selectedBackup = backupTarget.getValue() == null ? null : backupTarget.getValue().jar();
        LinkedHashSet<Path> known = new LinkedHashSet<>(config.getKnownServerJars()); if (config.getServerJar() != null) known.add(config.getServerJar());
        List<LocalServerTarget> targets = known.stream().map(path -> path.toAbsolutePath().normalize()).filter(Files::isRegularFile).map(LocalServerTarget::new).toList(); serverTargets.setAll(targets);
        selectTarget(compatibilityTarget, selectedCompat); selectTarget(backupTarget, selectedBackup); updateCompatibilityState(); updateBackupState();
    }
    private void selectTarget(ComboBox<LocalServerTarget> combo, Path previous) {
        Path wanted = previous != null ? previous : config.getServerJar(); LocalServerTarget match = wanted == null ? null : serverTargets.stream().filter(target -> target.jar().equals(wanted.toAbsolutePath().normalize())).findFirst().orElse(null);
        if (match != null) combo.getSelectionModel().select(match); else if (!serverTargets.isEmpty()) combo.getSelectionModel().selectFirst(); else combo.getSelectionModel().clearSelection();
    }
    private void chooseExistingServer() {
        FileChooser chooser = new FileChooser(); chooser.setTitle("Minecraft sunucu JAR dosyasını seç"); chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("JAR dosyaları", "*.jar")); File selected = chooser.showOpenDialog(compatibilityTarget.getScene().getWindow());
        if (selected == null) return; Path jar = selected.toPath().toAbsolutePath().normalize(); config.setServerJar(jar); manager.configure(jar); try { config.save(); installedJar.accept(jar, config.getMemoryMb()); refreshServerTargets(); compatibilityTarget.getSelectionModel().select(serverTargets.stream().filter(target -> target.jar().equals(jar)).findFirst().orElse(null)); backupTarget.getSelectionModel().select(compatibilityTarget.getValue()); } catch (IOException error) { error(error.getMessage()); }
    }
    private void updateCompatibilityState() { LocalServerTarget target = compatibilityTarget.getValue(); compatibilityState.setText(target == null ? "Kayıtlı yerel sunucu bulunamadı; JAR Seç düğmesini kullan." : "Senkronize: " + target.folder()); }
    private void updateBackupState() { LocalServerTarget target = backupTarget.getValue(); backupState.setText(target == null ? "Kayıtlı yerel sunucu bulunamadı." : "Bu sunucunun yedek klasörü: " + target.folder().resolve("backups")); }

    private Node backupView() {
        ListView<Path> list = new ListView<>(backups); list.setCellFactory(v -> new ListCell<>() { protected void updateItem(Path path, boolean empty) { super.updateItem(path, empty); if (empty || path == null) setText(null); else try { setText(path.getFileName() + "  •  " + Files.size(path) / 1024 / 1024 + " MB" + note(path)); } catch (IOException error) { setText(path.getFileName().toString()); } } }); VBox.setVgrow(list, Priority.ALWAYS);
        backupTarget.setItems(serverTargets); backupTarget.setMaxWidth(Double.MAX_VALUE); backupTarget.setPromptText("Yedekleri gösterilecek sunucuyu seç"); backupTarget.setOnAction(event -> { updateBackupState(); refreshBackups(); }); HBox.setHgrow(backupTarget, Priority.ALWAYS);
        Button choose = button("JAR Seç", "secondary"), create = button("Yeni Yedek", "primary"), refresh = button("Yenile", "secondary"), annotate = button("Not Ekle", "secondary"), restore = button("Geri Yükle", "secondary"), delete = button("Yedeği Sil", "danger"), archive = button("Eski Yedekleri Arşivle", "secondary"); Spinner<Integer> keep = new Spinner<>(1, 100, 10);
        choose.setOnAction(event -> chooseExistingServer()); create.setOnAction(event -> createBackup()); refresh.setOnAction(event -> refreshBackups()); annotate.setOnAction(event -> addBackupNote(list.getSelectionModel().getSelectedItem())); restore.setOnAction(event -> restoreBackup(list.getSelectionModel().getSelectedItem())); delete.setOnAction(event -> deleteBackup(list.getSelectionModel().getSelectedItem())); archive.setOnAction(event -> archiveOldBackups(keep.getValue()));
        HBox serverRow = new HBox(8, backupTarget, choose, create, refresh); HBox actions = new HBox(8, annotate, restore, delete, new Label("Son"), keep, new Label("yedek kalsın"), archive); serverRow.setAlignment(Pos.CENTER_LEFT); actions.setAlignment(Pos.CENTER_LEFT);
        backupState.getStyleClass().add("muted"); Label hosted = new Label("Exaroton ve Aternos resmî API'leri dünya yedeğini indirmeye izin vermediği için burada yalnızca erişilebilen yerel sunucular gösterilir."); hosted.setWrapText(true); hosted.getStyleClass().add("muted"); refreshServerTargets(); return page(card("SUNUCUYA ÖZEL YEDEK MERKEZİ", serverRow, backupState, actions, hosted, list));
    }
    private void refreshBackups() { LocalServerTarget target = backupTarget.getValue(); if (target == null) { backups.clear(); updateBackupState(); return; } Path dir = target.folder().resolve("backups"); try { if (!Files.isDirectory(dir)) { backups.clear(); updateBackupState(); return; } try (var files = Files.list(dir)) { backups.setAll(files.filter(path -> path.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".zip")).sorted(Comparator.comparing(this::modified).reversed()).toList()); } updateBackupState(); } catch (IOException error) { error(error.getMessage()); } }
    private void createBackup() { LocalServerTarget target = backupTarget.getValue(); if (target == null) { error("Önce yedeklenecek yerel sunucuyu seç."); return; } boolean managed = sameFolder(manager.getServerFolder(), target.folder()); Task<Path> task = new Task<>() { protected Path call() throws Exception { return managed ? manager.createBackup() : createOfflineBackup(target.folder()); } }; backupState.setText("Yedekleniyor: " + target.name()); task.setOnSucceeded(event -> { refreshBackups(); info("Yedek hazır", task.getValue().toString()); }); task.setOnFailed(event -> { updateBackupState(); error(rootMessage(task.getException())); }); run(task, "nextgen-backup"); }
    private void addBackupNote(Path backup) { if (backup == null) return; TextInputDialog dialog = new TextInputDialog(note(backup).replace("  •  ", "")); dialog.setHeaderText("Yedek notu"); dialog.showAndWait().ifPresent(value -> { try { Files.writeString(noteFile(backup), value, StandardCharsets.UTF_8); refreshBackups(); } catch (IOException error) { error(error.getMessage()); } }); }
    private String note(Path backup) { try { Path note = noteFile(backup); return Files.exists(note) ? "  •  " + Files.readString(note).strip() : ""; } catch (IOException error) { return ""; } }
    private Path noteFile(Path backup) { return backup.resolveSibling(backup.getFileName() + ".note"); }
    private FileTimeBox modified(Path path) { try { return new FileTimeBox(Files.getLastModifiedTime(path).toMillis()); } catch (IOException error) { return new FileTimeBox(0); } }
    private void deleteBackup(Path backup) { LocalServerTarget target = backupTarget.getValue(); if (backup == null || target == null) return; Path directory = target.folder().resolve("backups").toAbsolutePath().normalize(), resolved = backup.toAbsolutePath().normalize(); if (!isSafeBackupPath(directory, resolved)) { error("Güvenli olmayan yedek yolu engellendi."); return; } if (!confirm(resolved.getFileName() + " kalıcı olarak silinsin mi?")) return; try { Files.delete(resolved); Files.deleteIfExists(noteFile(resolved)); refreshBackups(); } catch (IOException error) { error("Yedek silinemedi: " + error.getMessage()); } }
    private void archiveOldBackups(int keep) { if (backups.size() <= keep) return; if (!confirm((backups.size() - keep) + " eski yedek arşiv klasörüne taşınsın mı?")) return; try { Path archive = backups.get(0).getParent().resolve("archive"); Files.createDirectories(archive); for (Path path : new ArrayList<>(backups.subList(keep, backups.size()))) { Path note = noteFile(path); Files.move(path, archive.resolve(path.getFileName()), StandardCopyOption.REPLACE_EXISTING); if (Files.exists(note)) Files.move(note, archive.resolve(note.getFileName()), StandardCopyOption.REPLACE_EXISTING); } refreshBackups(); } catch (IOException error) { error(error.getMessage()); } }
    private void restoreBackup(Path backup) { LocalServerTarget target = backupTarget.getValue(); if (backup == null || target == null) return; if (manager.isRunning() && sameFolder(manager.getServerFolder(), target.folder())) { error("Bu sunucunun yedeğini geri yüklemeden önce sunucuyu durdur."); return; } if (!confirm("Seçili yedekteki dünyalar " + target.name() + " sunucusuna geri yüklensin mi? Mevcut dünyalar güvenlik klasörüne taşınacak.")) return; Task<Void> task = new Task<>() { protected Void call() throws Exception { restoreWorlds(backup, target.folder()); return null; } }; task.setOnSucceeded(event -> info("Geri yükleme tamamlandı", "Mevcut dünyaların güvenlik kopyası korunuyor.")); task.setOnFailed(event -> error(rootMessage(task.getException()))); run(task, "backup-restore"); }
    private void restoreWorlds(Path backup, Path root) throws IOException { Path safety = root.resolve("restore-safety-" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"))); Files.createDirectories(safety); for (String name : List.of("world", "world_nether", "world_the_end")) if (Files.exists(root.resolve(name))) Files.move(root.resolve(name), safety.resolve(name)); boolean found = false; try (ZipInputStream zip = new ZipInputStream(Files.newInputStream(backup))) { ZipEntry entry; while ((entry = zip.getNextEntry()) != null) { String name = entry.getName().replace('\\', '/'); if (!(name.startsWith("world/") || name.startsWith("world_nether/") || name.startsWith("world_the_end/"))) continue; Path destination = root.resolve(name).normalize(); if (!destination.startsWith(root)) throw new IOException("Güvensiz ZIP yolu engellendi"); if (entry.isDirectory()) Files.createDirectories(destination); else { Files.createDirectories(destination.getParent()); Files.copy(zip, destination, StandardCopyOption.REPLACE_EXISTING); } found = true; } } if (!found) throw new IOException("Yedekte dünya verisi bulunamadı. Güvenlik kopyası " + safety + " klasöründe."); }
    static Path createOfflineBackup(Path root) throws IOException {
        Path directory = root.resolve("backups"); Files.createDirectories(directory); Path output = directory.resolve("backup-" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss")) + ".zip");
        try (ZipOutputStream zip = new ZipOutputStream(Files.newOutputStream(output))) { for (String name : List.of("world", "world_nether", "world_the_end", "server.properties", "whitelist.json", "ops.json", "banned-players.json", "banned-ips.json")) { Path source = root.resolve(name); if (Files.isDirectory(source)) { try (var files = Files.walk(source)) { for (Path file : files.filter(Files::isRegularFile).toList()) addBackupFile(root, file, zip); } } else if (Files.isRegularFile(source)) addBackupFile(root, source, zip); } } return output;
    }
    private static void addBackupFile(Path root, Path file, ZipOutputStream zip) throws IOException { String name = root.relativize(file).toString().replace('\\', '/'); zip.putNextEntry(new ZipEntry(name)); Files.copy(file, zip); zip.closeEntry(); }
    static boolean sameFolder(Path first, Path second) { return first != null && second != null && first.toAbsolutePath().normalize().equals(second.toAbsolutePath().normalize()); }
    static boolean isSafeBackupPath(Path directory, Path backup) { if (directory == null || backup == null || backup.getFileName() == null) return false; Path safeDirectory = directory.toAbsolutePath().normalize(), safeBackup = backup.toAbsolutePath().normalize(); return safeBackup.getParent() != null && safeBackup.getParent().equals(safeDirectory) && safeBackup.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".zip"); }

    private Node optimizationView() { ListView<String> list = new ListView<>(suggestions); VBox.setVgrow(list, Priority.ALWAYS); Button analyze = button("AYARLARI ANALİZ ET", "primary"), apply = button("Güvenli Önerileri Uygula", "secondary"); analyze.setOnAction(event -> analyzeOptimization()); apply.setOnAction(event -> applyOptimization()); Label note = new Label("Asistan server.properties değerlerini RAM, oyuncu sınırı, görüş ve simülasyon mesafesine göre değerlendirir. Uygulamadan önce .optimization-backup alınır."); note.getStyleClass().add("muted"); return page(card("AKILLI OPTİMİZASYON ASİSTANI", note, new HBox(8, analyze, apply), list)); }
    private void analyzeOptimization() { suggestions.clear(); Path file = serverProperties(); if (file == null) return; Properties p = load(file); int view = number(p, "view-distance", 10), sim = number(p, "simulation-distance", 10), max = number(p, "max-players", 20), ram = config.getMemoryMb(); if (view > 10) suggestions.add("YÜKSEK ETKİ • view-distance=" + view + " → 8-10 aralığı TPS'yi rahatlatabilir."); if (sim > 8) suggestions.add("YÜKSEK ETKİ • simulation-distance=" + sim + " → 6 önerilir."); if (max > 30 && ram < 4096) suggestions.add("RAM • " + max + " oyuncu için " + ram + " MB düşük olabilir; en az 4096 MB düşün."); if (Boolean.parseBoolean(p.getProperty("sync-chunk-writes", "true"))) suggestions.add("DİSK • sync-chunk-writes=false modern Paper sunucularda disk beklemesini azaltabilir."); if (suggestions.isEmpty()) suggestions.add("Harika: Temel ayarlarda belirgin bir performans sorunu görünmüyor."); suggestions.add("NOT • Gerçek sonuç için Pro Araçlar bölümündeki TPS ve RAM grafiğini yük altında izle."); }
    private void applyOptimization() { Path file = serverProperties(); if (file == null || !confirm("Güvenli performans ayarları uygulansın mı?")) return; try { Files.copy(file, file.resolveSibling("server.properties.optimization-backup"), StandardCopyOption.REPLACE_EXISTING); Properties p = load(file); p.setProperty("view-distance", Integer.toString(Math.min(8, number(p, "view-distance", 10)))); p.setProperty("simulation-distance", Integer.toString(Math.min(6, number(p, "simulation-distance", 10)))); p.setProperty("sync-chunk-writes", "false"); try (Writer writer = Files.newBufferedWriter(file)) { p.store(writer, "AeroMC optimized settings"); } analyzeOptimization(); info("Optimizasyon uygulandı", "Değişiklikler yeniden başlatmada etkinleşecek."); } catch (IOException error) { error(error.getMessage()); } }

    private Node remoteView() {
        TextField username = new TextField(); username.setPromptText("Kullanıcı adı"); PasswordField password = new PasswordField(); password.setPromptText("En az 12 karakterli parola"); ComboBox<RemoteControlService.Role> role = new ComboBox<>(FXCollections.observableArrayList(RemoteControlService.Role.values())); role.getSelectionModel().select(RemoteControlService.Role.VIEWER); Button add = button("Kullanıcı Oluştur", "primary");
        ListView<String> userList = new ListView<>(users); Button remove = button("Seçileni Sil", "danger"); add.setOnAction(event -> { try { remote.createUser(username.getText(), password.getText().toCharArray(), role.getValue()); username.clear(); password.clear(); refreshSecurity(); } catch (Exception error) { error(error.getMessage()); } }); remove.setOnAction(event -> { String selected = userList.getSelectionModel().getSelectedItem(); if (selected != null) { remote.deleteUser(selected.split(" • ")[0]); refreshSecurity(); } });
        HBox userRow = new HBox(8, username, password, role, add, remove); HBox.setHgrow(username, Priority.ALWAYS); HBox.setHgrow(password, Priority.ALWAYS);
        Label roles = new Label("VIEWER: yalnızca durumu görür  •  MODERATOR: mesaj, kick ve ban kullanır  •  ADMIN: başlatma, durdurma, yedek ve konsol dahil tam yetkilidir."); roles.setWrapText(true); roles.getStyleClass().add("muted"); userList.setPrefHeight(92); userList.setMinHeight(92);
        Spinner<Integer> port = new Spinner<>(1024, 65535, 8765); CheckBox lan = new CheckBox("Yerel ağdaki telefonlara aç"); Button start = button("Uzaktan Erişimi Başlat", "primary"), stop = button("Durdur", "danger"), open = button("Tarayıcıda Aç", "secondary");
        start.setOnAction(event -> { if (remote.listUsers().isEmpty()) { error("Önce 1. adımdan en az bir kullanıcı oluştur."); return; } if (lan.isSelected() && !confirm("LAN erişimi yalnızca güvendiğin özel Wi-Fi ağında kullanılmalı. İnternete port yönlendirmesi yapma. Devam edilsin mi?")) return; try { remote.start(lan.isSelected(), port.getValue()); refreshSecurity(); info("HTTPS uzaktan erişim hazır", "Bağlantı TLS ile şifreleniyor. Yerel sertifika herkese açık bir sertifika otoritesinden gelmediği için tarayıcı ilk bağlantıda uyarı gösterebilir. Devam etmeden önce tarayıcıdaki SHA-256 parmak izini AeroMC'deki değerle karşılaştır.\n\n" + remote.getCertificateFingerprint()); } catch (Exception error) { error(error.getMessage()); } }); stop.setOnAction(event -> { remote.stop(); refreshSecurity(); }); open.setOnAction(event -> { if (!remote.isRunning()) { error("Önce uzaktan erişimi başlat."); return; } try { hostServices.showDocument(remote.getAddress()); } catch (Exception error) { error("Tarayıcı açılamadı: " + error.getMessage()); } }); remoteState.getStyleClass().add("remote-address");
        Button copy = button("Adresi Kopyala", "secondary"); copy.setOnAction(event -> { if (remote.isRunning()) clipboard(remote.getAddress()); });
        Button copyFingerprint = button("TLS Parmak İzini Kopyala", "secondary"); copyFingerprint.setOnAction(event -> { if (!remote.getCertificateFingerprint().isBlank()) clipboard(remote.getCertificateFingerprint()); });
        FlowPane service = new FlowPane(8, 8, new Label("Port"), port, lan, start, stop, open, copy, copyFingerprint); service.setAlignment(Pos.CENTER_LEFT);
        Label connectionHelp = new Label("Aynı bilgisayar: LAN kutusunu işaretleme ve Tarayıcıda Aç'a bas.  •  Telefon/başka bilgisayar: LAN kutusunu aç, cihazı aynı Wi-Fi'a bağla ve HTTPS adresini yaz. İlk bağlantıda yerel sertifika uyarısı normaldir; SHA-256 parmak izini karşılaştırmadan ilerleme."); connectionHelp.setWrapText(true); connectionHelp.getStyleClass().add("muted"); remoteState.setWrapText(true); remoteTlsState.setWrapText(true); remoteTlsState.getStyleClass().add("muted");

        TableView<RemoteControlService.AuditEntry> auditTable = new TableView<>(audit); auditTable.getColumns().add(auditColumn("Zaman", entry -> formatAuditTime(entry.time()))); auditTable.getColumns().add(auditColumn("Kullanıcı", RemoteControlService.AuditEntry::user)); auditTable.getColumns().add(auditColumn("Olay", entry -> friendlyAuditAction(entry.action()))); auditTable.getColumns().add(auditColumn("Hedef", RemoteControlService.AuditEntry::target)); auditTable.getColumns().add(auditColumn("Sonuç", entry -> friendlyAuditResult(entry.result()))); auditTable.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN); VBox.setVgrow(auditTable, Priority.ALWAYS);
        Button refresh = button("Günlüğü Yenile", "secondary"), clear = button("Günlüğü Temizle", "danger"); refresh.setOnAction(event -> refreshSecurity()); clear.setOnAction(event -> { if (!confirm("Güvenlik günlüğü temizlensin mi?")) return; try { remote.clearAudit(); refreshSecurity(); } catch (IOException error) { error(error.getMessage()); } });
        Label auditHelp = new Label("Bu günlük; kimin giriş denediğini, hangi komutu gönderdiğini ve işlemin başarılı mı reddedilmiş mi olduğunu gösterir. Parolalar ve API anahtarları kaydedilmez. DENIED başarısız/yetkisiz giriş, RATE LIMIT ise 5 hatalı denemeden sonra geçici engel demektir."); auditHelp.setWrapText(true); auditHelp.getStyleClass().add("muted");
        VBox first = card("1 • UZAKTAN ERİŞİM KULLANICISI OLUŞTUR", roles, userRow, userList); first.setMinHeight(200); VBox second = card("2 • HTTPS BAĞLANTISINI BAŞLAT", connectionHelp, service, remoteState, remoteTlsState); second.setMinHeight(190); VBox third = card("3 • GÜVENLİK GÜNLÜĞÜ", auditHelp, new HBox(8, refresh, clear), auditTable); VBox.setVgrow(third, Priority.ALWAYS);
        VBox page = page(first, second, third); VBox.setVgrow(first, Priority.NEVER); VBox.setVgrow(second, Priority.NEVER); VBox.setVgrow(third, Priority.ALWAYS); return scrollable(page);
    }
    private void refreshSecurity() { users.setAll(remote.listUsers().entrySet().stream().map(e -> e.getKey() + " • " + e.getValue()).toList()); audit.setAll(remote.readAuditEntries(200)); remoteState.setText(remote.isRunning() ? "Açılacak güvenli adres: " + remote.getAddress() : "Uzaktan erişim kapalı"); remoteTlsState.setText(remote.getCertificateFingerprint().isBlank() ? "TLS kimliği ilk başlatmada oluşturulacak" : "TLS 1.2/1.3 • SHA-256: " + remote.getCertificateFingerprint()); }
    private void clipboard(String value) { javafx.scene.input.ClipboardContent content = new javafx.scene.input.ClipboardContent(); content.putString(value); javafx.scene.input.Clipboard.getSystemClipboard().setContent(content); }
    private TableColumn<RemoteControlService.AuditEntry, String> auditColumn(String title, java.util.function.Function<RemoteControlService.AuditEntry, String> value) { TableColumn<RemoteControlService.AuditEntry, String> column = new TableColumn<>(title); column.setCellValueFactory(row -> new ReadOnlyStringWrapper(value.apply(row.getValue()))); return column; }
    private String formatAuditTime(String value) { try { return LocalDateTime.parse(value).format(DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss")); } catch (Exception ignored) { return value; } }
    private String friendlyAuditAction(String action) { return switch (action) { case "remote-start" -> "Uzaktan erişim açıldı"; case "remote-stop" -> "Uzaktan erişim kapandı"; case "user-create" -> "Kullanıcı oluşturuldu"; case "user-delete" -> "Kullanıcı silindi"; case "login-failed" -> "Hatalı giriş"; case "login-blocked" -> "Giriş geçici engellendi"; case "audit-cleared" -> "Günlük temizlendi"; case "start" -> "Sunucu başlatma"; case "stop" -> "Sunucu durdurma"; case "restart" -> "Sunucu yeniden başlatma"; case "backup" -> "Yedek alma"; case "say" -> "Duyuru"; case "kick" -> "Oyuncu atma"; case "ban" -> "Oyuncu yasaklama"; case "command" -> "Konsol komutu"; default -> action; }; }
    private String friendlyAuditResult(String result) { if ("OK".equals(result)) return "Başarılı"; if ("DENIED".equals(result)) return "Reddedildi"; if ("RATE_LIMIT".equals(result)) return "Geçici engel"; return result.startsWith("ERROR") ? "Hata: " + result.substring(5).strip() : result; }

    public void shutdown() { remote.stop(); }
    private Path serverProperties() { Path root = manager.getServerFolder(); if (root == null) { error("Önce yerel server.jar seç."); return null; } Path file = root.resolve("server.properties"); if (!Files.exists(file)) { error("server.properties bulunamadı."); return null; } return file; }
    private Properties load(Path file) { Properties p = new Properties(); try (Reader r = Files.newBufferedReader(file)) { p.load(r); } catch (IOException ignored) { } return p; }
    private int number(Properties p, String key, int fallback) { try { return Integer.parseInt(p.getProperty(key, Integer.toString(fallback))); } catch (Exception error) { return fallback; } }
    private int requiredJava(String version) { try { if (version.matches("^(2[6-9]|[3-9][0-9])\\..*")) return 25; String[] p = version.split("\\."); int minor = p.length > 1 ? Integer.parseInt(p[1]) : 0, patch = p.length > 2 ? Integer.parseInt(p[2].replaceAll("[^0-9].*", "")) : 0; return minor > 20 || minor == 20 && patch >= 5 ? 21 : minor >= 17 ? 17 : 8; } catch (Exception error) { return 17; } }
    private static String string(JsonObject object, String key, String fallback) { return object.has(key) && object.get(key).isJsonPrimitive() ? object.get(key).getAsString() : fallback; }
    private static String stem(Path file) { String name = file.getFileName().toString(); return name.toLowerCase(Locale.ROOT).endsWith(".jar") ? name.substring(0, name.length() - 4) : name; }
    private String encode(String value) { return URLEncoder.encode(value, StandardCharsets.UTF_8); }
    private long modifiedValue(Path path) { try { return Files.getLastModifiedTime(path).toMillis(); } catch (IOException error) { return 0; } }
    private Tab tab(String title, Node content) { Tab tab = new Tab(title, content); tab.setClosable(false); return tab; }
    private VBox page(Node... nodes) { VBox page = new VBox(14, nodes); page.setPadding(new Insets(18)); return page; }
    private ScrollPane scrollable(Node content) { ScrollPane scroll = new ScrollPane(content); scroll.setFitToWidth(true); scroll.setFitToHeight(false); scroll.getStyleClass().add("control-scroll"); return scroll; }
    private VBox card(String title, Node... nodes) { Label label = new Label(title); label.getStyleClass().add("section-title"); VBox card = new VBox(11, label); card.getChildren().addAll(nodes); card.getStyleClass().add("card"); return card; }
    private Button button(String text, String style) { Button button = new Button(text); button.getStyleClass().add(style); return button; }
    private void addField(GridPane grid, int column, String title, Node field) { VBox box = new VBox(4, new Label(title), field); grid.add(box, column, 0); GridPane.setHgrow(box, Priority.ALWAYS); }
    private TableColumn<CompatResult, String> col(String title, java.util.function.Function<CompatResult, String> value) { TableColumn<CompatResult, String> column = new TableColumn<>(title); column.setCellValueFactory(row -> new ReadOnlyStringWrapper(value.apply(row.getValue()))); return column; }
    private void run(Task<?> task, String name) { Thread thread = new Thread(task, "aeromc-" + name); thread.setDaemon(true); thread.start(); }
    private boolean confirm(String text) { Alert alert = new Alert(Alert.AlertType.CONFIRMATION, LanguageManager.text(text), ButtonType.YES, ButtonType.NO); alert.setHeaderText(LanguageManager.text("Onay gerekiyor")); return alert.showAndWait().orElse(ButtonType.NO) == ButtonType.YES; }
    private void error(String text) { if (!Platform.isFxApplicationThread()) { Platform.runLater(() -> error(text)); return; } Alert alert = new Alert(Alert.AlertType.ERROR, LanguageManager.text(text == null ? "Bilinmeyen hata" : text), ButtonType.OK); alert.setHeaderText(LanguageManager.text("İşlem tamamlanamadı")); alert.showAndWait(); }
    private void info(String title, String text) { Alert alert = new Alert(Alert.AlertType.INFORMATION, LanguageManager.text(text), ButtonType.OK); alert.setHeaderText(LanguageManager.text(title)); alert.showAndWait(); }
    private String rootMessage(Throwable error) { Throwable cause = error; while (cause != null && cause.getCause() != null) cause = cause.getCause(); return cause == null || cause.getMessage() == null ? "Bilinmeyen hata" : cause.getMessage(); }
    record CompatResult(String file, String type, String level, String message) { }
    private record JarInfo(String file, String type, String id, String version, List<String> required, String error) { }
    private record SetupResult(Path jar, SparkInstaller.InstallResult spark) { }
    private record LocalServerTarget(Path jar) { Path folder() { return jar.getParent(); } String name() { Path folder = folder(); return folder == null ? jar.getFileName().toString() : folder.getFileName().toString(); } @Override public String toString() { return name() + "  •  " + folder(); } }
    private record FileTimeBox(long value) implements Comparable<FileTimeBox> { public int compareTo(FileTimeBox other) { return Long.compare(value, other.value); } }
}
